/**
 * (c) 2010-present DEMOS plan GmbH.
 *
 * This file is part of the package demosplan,
 * for more information see the license file.
 *
 * All rights reserved
 */

/**
 * (c) 2010-present DEMOS E-Partizipation GmbH.
 *
 * This file is part of the package demosplan,
 * for more information see the license file.
 *
 * All rights reserved
 */

/**
 * Hide a form field generated by plugins/FloodControl visually + for screen readers.
 * This is done via javascript to make it harder for bots to spot the honeypot.
 */
export default function FloodControlField () {
  (function () {
    const field = document.querySelector('[data-enhance-url-field]')
    if (field) {
      field.setAttribute('hidden', 'true')
    }
  })()
}
