/**
 * Hide a form field generated by plugins/FloodControl visually + for screen readers.
 * This is done via javascript to make it harder for bots to spot the honeypot.
 */
export default function FloodControlField () {
  (function () {
    const field = document.querySelector('[data-enhance-url-field]')
    if (field) {
      field.setAttribute('hidden', 'true')
    }
  })()
}
