doctrine_migrations:
    migrations_paths:
        Application\Migrations: "%kernel.project_dir%/demosplan/DemosPlanCoreBundle/DoctrineMigrations"
    storage:
        table_storage:
            table_name: migration_versions
            # This custom column name can be deleted once every project applied doctrine migrations 3 update
            executed_at_column_name: 'migration_executed_at'
    organize_migrations: "BY_YEAR_AND_MONTH"
    custom_template: "%kernel.project_dir%/demosplan/DemosPlanCoreBundle/DoctrineMigrations/migration.tpl"
