doctrine:
    dbal:
        #url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'
        default_connection: dplan
        connections:
            dplan:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
            dplan_install:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_install_user%"
                password: "%database_install_password%"
                charset:  UTF8
        types:
            dplan.stored_query: \demosplan\DemosPlanCoreBundle\Doctrine\Type\StoredQueryType
            dplan.custom_field_configuration: \demosplan\DemosPlanCoreBundle\Doctrine\Type\CustomFieldType
            dplan.custom_fields_value: \demosplan\DemosPlanCoreBundle\Doctrine\Type\CustomFieldValueType

    orm:
        auto_generate_proxy_classes: true
        default_entity_manager: default
        #enable_lazy_ghost_objects: true # needs to be enabled for symfony 6, not before, needs doctrine/persistence > 3.1
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                connection: dplan
                auto_mapping: true
                metadata_cache_driver:
                    type: pool
                    pool: doctrine.cache_pool
                query_cache_driver:
                    type: pool
                    pool: doctrine.cache_pool
            install:
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                connection: dplan_install

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            default_connection: dplan
            connections:
                dplan:
                    dbname_suffix: '_test%env(default::TEST_TOKEN)%'
                    driver: pdo_sqlite
                    path: "%kernel.cache_dir%/__DBNAME__.db"
                    charset: UTF8
                    memory: false
                    user: test

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            metadata_cache_driver:
                type: pool
                pool:
                    doctrine.system_cache_pool
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

framework:
    cache:
        pools:
            doctrine.result_cache_pool:
                adapter: cache.app
            doctrine.system_cache_pool:
                adapter: cache.system
