# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    assets: ~
    #esi: true
    secret: '%env(APP_SECRET)%'
    form: ~
    csrf_protection: ~
    enabled_locales: ['de']
    validation: { enable_annotations: true }
    trusted_proxies: "%proxy_trusted%"
    trusted_headers: [ 'x-forwarded-for', 'x-forwarded-host', 'x-forwarded-proto', 'x-forwarded-port', 'x-forwarded-prefix' ]
    trusted_hosts: ~
    #csrf_protection: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: 'demosplan\DemosPlanCoreBundle\Logic\SessionHandler'
        cookie_secure: '%https_only%'
        # could not be strict, as otherwise keycloak login does not work with an "invalid state" error
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    fragments:       ~
    #fragments: true
    http_method_override: false
    php_errors:
        log: true
    http_client:
        default_options:
            max_redirects: 7
            proxy: '%proxy_dsn%'

    request:
        formats:
            jsonapi: [ 'application/vnd.api+json' ]

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
