lexik_jwt_authentication:
    encoder:
        # encryption algorithm used by the encoder service
        signature_algorithm: HS256
    # recipe wants this, we currently use our passphrase
    #secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    secret_key: '%env(JWT_PASSPHRASE)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 259200
    # set custom header for jwt to be able to use it together with basic header authorisation
    token_extractors:
        authorization_header:
            name: 'X-JWT-Authorization'
