lexik_jwt_authentication:
    encoder:
        # encryption algorithm used by the encoder service
        signature_algorithm: HS256
    secret_key: '%env(JWT_PASSPHRASE)%'
    token_ttl: 259200
    # set custom header for jwt to be able to use it together with basic header authorisation
    token_extractors:
        authorization_header:
            name: 'X-JWT-Authorization'
