# See the configuration reference at https://symfony.com/bundles/SchebTwoFactorBundle/5.x/configuration.html
scheb_two_factor:
    security_tokens:
        - Symfony\Component\Security\Http\Authenticator\Token\PostAuthenticationToken
    totp:
        enabled: true
        issuer: '%project_name%'
        template: '@DemosPlanCore/DemosPlanUser/2fa.html.twig'
    email:
        enabled: true
        digits: 6
        mailer: 'demosplan\DemosPlanCoreBundle\Mailer\TwoFactorMailer'
        template: '@DemosPlanCore/DemosPlanUser/2fa.html.twig'
