sentry:
    dsn: "%sentry_dsn%"
    options:
        attach_stacktrace: true
        release: '%demosplan.project_name%@%project_version%'
        traces_sample_rate: "%sentry_traces_sample_rate%"
    register_error_listener: false # Disables the ErrorListener to avoid duplicate entries

services:
    Sentry\Monolog\Handler:
        arguments:
            $hub: '@Sentry\State\HubInterface'
            $level: "%sentry_loglevel%"
            $bubble: false
