framework:
    default_locale: "%locale%"
    translator:
        default_path: '%demosplan.project_dir%/translations'
        fallback: de
        paths:
            - '%kernel.project_dir%/translations'
