twig:
    debug:            '%kernel.debug%'
    exception_controller: null
    strict_variables: '%kernel.debug%'
    globals:
        alternative_login_use_testuser: '%alternative_login_use_testuser%'
        alternative_login_testuser_defaultpass: '%alternative_login_testuser_defaultpass%'
        tracking_enabled: '%piwik_enable%'
        sentry_dsn: '%sentry_dsn%'
    form_themes:
        - '@DemosPlanCore/form/styled_fields.html.twig'
    default_path: '%kernel.project_dir%/templates'

when@test:
    twig:
        strict_variables: true
