when@dev: &dev
    # See full configuration: https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#full-default-bundle-configuration
    zenstruck_foundry:
        database_resetter:
            orm:
                reset_mode: schema # enables resetting with migrations
        # Whether to auto-refresh proxies by default (https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#auto-refresh)
        auto_refresh_proxies: true
        faker:
            locale: de_DE
#            seed: null
        make_factory:
            # Namespace to use for make:factory. Is overridden by --namespace option
            default_namespace: 'DataGenerator\Factory'
when@test: *dev
