runner:
#    eslint:
#        cmd: "node_modules/.bin/eslint -c config/linters/eslintrc.js demosplan client"

    phpstan:
        cmd: "DEVELOPMENT_CONTAINER=1 php bin/console dplan:phpstan --ci -l0"
        format: "phpstan"
        level: error
    phpstan-level1:
        cmd: "DEVELOPMENT_CONTAINER=1 php bin/console dplan:phpstan --ci -l1"
        format: "phpstan"
        level: error
    phpstan-level2:
        cmd: "DEVELOPMENT_CONTAINER=1 php bin/console dplan:phpstan --ci -l2"
        format: "phpstan"
        level: info
