runner:
#    eslint:
#        cmd: "node_modules/.bin/eslint -c config/linters/eslintrc.js demosplan client"

    phpstan:
        cmd: "DEVELOPMENT_CONTAINER=1 php bin/diplanbau dplan:phpstan --ci -l2"
