runner:
    eslint:
        cmd: "ESLINT_USE_FLAT_CONFIG=false eslint -c eslintrc.js --ext .js,.vue demosplan client"

    phpstan:
        cmd: "DEVELOPMENT_CONTAINER=1 php bin/test dplan:phpstan --ci -l1"
