runner:
    eslint:
        cmd: "yarn eslint client"

    phpstan:
        cmd: "vendor/bin/phpstan analyse -c phpstan.neon demosplan -l 1 --error-format=checkstyle --no-progress"
        format: checkstyle
