jobs:
  Job1:
    name: Job 1
    steps: []
  Job2:
    name: Job 2
    dependencies:
      - Job1
    repositories:
      - git@github.com:demos-europe/demosplan-project-diplanbau.git:
          path: projects/diplanbau
          enabled: true
      - main:
          enabled: false
