jobs:
  Job1:
    name: Job 1
    steps: []
    files-publication:
      - path: .
        share-with-jobs: true
        publish-artifact: false
  Job2:
    name: Job 2
    dependencies:
      - Job1:
          files:
            - .
    repositories:
      - git@github.com:demos-europe/demosplan-project-diplanbau.git:
          path: projects/diplanbau
          enabled: true
      - main:
          enabled: false
  Job3:
    name: Job 3
    dependencies:
      - Job1:
          files:
            - .
  Job4:
    name: Job 4
    dependencies:
      - Job1:
          files:
            - .
