checksumBehavior: reset

enableTelemetry: false

nodeLinker: node-modules

npmRegistries:
  "https://www.dev.diplanung.de/DefaultCollection/DiPlanKarten/_packaging/karten.feed/npm/registry/":
    npmAuthIdent: "${ADO_NPM_AUTH_IDENT}"
    npmAlwaysAuth: true

npmScopes:
  init:
    npmAlwaysAuth: true
    npmAuthIdent: "${ADO_NPM_AUTH_IDENT}"
    npmRegistryServer: "https://www.dev.diplanung.de/DefaultCollection/DiPlanKarten/_packaging/karten.feed/npm/registry/"
