parameters:
    container.autowiring.strict_mode: true
    container.dumper.inline_class_loader: true

    # These parameters are set at build time but defined here for code completion
    demosplan.project_dir: ''
    demosplan.project_name: ''
    demosplan.project_version: ''

imports:
    - { resource: "@DemosPlanCoreBundle/Resources/config/allowedMimeTypes.yml" }
    - { resource: "@DemosPlanCoreBundle/Resources/config/elasticsearch.yml" }
    - { resource: "@DemosPlanCoreBundle/Resources/config/entity_content_change_fields_mapping.yml" }
    - { resource: "@DemosPlanCoreBundle/Resources/config/secrets.yml", ignore_errors: true }

    # do not change the ordering here, it matters! <3
    - { resource: "@DemosPlanCoreBundle/Resources/config/services_autowire.yml" }
    - { resource: "@DemosPlanCoreBundle/Resources/config/services_repositories.yml" }
    - { resource: "@DemosPlanCoreBundle/Resources/config/services.yml" }
    - { resource: "@DemosPlanCoreBundle/Resources/config/doctrine_extensions.yml" }
