# services to handle doctrine extensions
# import it in config.yml
services:
    # KernelRequest listener
#    extension.listener:
#        class: Acme\DemoBundle\Listener\DoctrineExtensionListener
#        calls:
#            - [ setContainer, [ @service_container ] ]
#        tags:
#            # translatable sets locale after router processing
#            - { name: kernel.event_listener, event: kernel.request, method: onLateKernelRequest, priority: -10 }
#            # loggable hooks user username if one is in security context
#            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
#            # translatable sets locale such as default application locale before command execute
#            - { name: kernel.event_listener, event: console.command, method: onConsoleCommand, priority: -10 }


    # Doctrine Extension listeners to handle behaviors
     gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: doctrine.event_subscriber }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]
