parameters:
    database_name: 'any_name'
    email_bounce_prefix: 'bobsh'
    email_bounce_domain: 'bounces-qs.bob-sh.de'
    email_system: 'testemail@mail.org'
    avscan_enable: false
    fileservice_filepath: "/tmp/uploads"
    doctrine.dbal.connection_factory.class: Liip\TestFixturesBundle\Factory\ConnectionFactory
    subdomain: 'hindsight'
    subdomains_allowed:
        - 'sh'
        - 'hindsight'
        - 'brandenburg'
    pipeline.ai.annotated.statement.pdf.created.id: "pipeline.ai.annotated.statement.pdf.created.id"
    pipeline.ai.annotated.statement.pdf.reviewed.id: "pipeline.ai.annotated.statement.pdf.reviewed.id"
    pipeline.demos.authorization: "pipeline.demos.authorization"
    pi.pipeline.segment.recognition.id: "pi.pipeline.segment.recognition.id"
    pi.pipeline.confirmed.segments.id: "pi.pipeline.confirmed.segments.id"
    project_prefix: 'dplan_test'
    honeypot_disabled: true
