services:

    _defaults:
        autowire: true
        autoconfigure: true

    # makes classes in demosplan/* available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    demosplan\DemosPlanAdminBundle\:
        resource: '../../../../demosplan/DemosPlanAdminBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../../../demosplan/DemosPlanAdminBundle/{Entity,Tests}'

    demosplan\DemosPlanAssessmentTableBundle\:
        resource: '../../../../demosplan/DemosPlanAssessmentTableBundle/*'
        exclude: '../../../../demosplan/DemosPlanAssessmentTableBundle/{Entity,Tests}'

    demosplan\DemosPlanCoreBundle\:
        resource: '../../../../demosplan/DemosPlanCoreBundle/*'
        exclude:
            - '../../../../demosplan/DemosPlanCoreBundle/{Entity,Tests,ResourceTypes,StoredQuery,Resources/config}'

    demosplan\DemosPlanDocumentBundle\:
        resource: '../../../../demosplan/DemosPlanDocumentBundle/*'
        exclude: '../../../../demosplan/DemosPlanDocumentBundle/{Entity,Tests}'

    demosplan\DemosPlanForumBundle\:
        resource: '../../../../demosplan/DemosPlanForumBundle/*'
        exclude: '../../../../demosplan/DemosPlanForumBundle/{Entity,Tests}'

    demosplan\DemosPlanMapBundle\:
        resource: '../../../../demosplan/DemosPlanMapBundle/*'
        exclude: '../../../../demosplan/DemosPlanMapBundle/{Entity,Tests}'

    demosplan\DemosPlanProcedureBundle\:
        resource: '../../../../demosplan/DemosPlanProcedureBundle/*'
        exclude: '../../../../demosplan/DemosPlanProcedureBundle/{Entity,Tests}'

    demosplan\DemosPlanReportBundle\:
        resource: '../../../../demosplan/DemosPlanReportBundle/*'
        exclude: '../../../../demosplan/DemosPlanReportBundle/{Entity,Tests}'

    demosplan\DemosPlanStatementBundle\:
        resource: '../../../../demosplan/DemosPlanStatementBundle/*'
        exclude: '../../../../demosplan/DemosPlanStatementBundle/{Entity,Tests}'

    demosplan\DemosPlanUserBundle\:
        resource: '../../../../demosplan/DemosPlanUserBundle/*'
        exclude: '../../../../demosplan/DemosPlanUserBundle/{Entity,Tests}'

############### Fixtures

    demosplan\DemosPlanCoreBundle\DataFixtures\ORM\ProdData\:
        autowire: true
        resource: '../../../../demosplan/DemosPlanCoreBundle/DataFixtures/ORM/ProdData'
        public: true
        tags: ['doctrine.fixture.orm']
    demosplan\DemosPlanCoreBundle\DataFixtures\ORM\TestData\:
        autowire: true
        resource: '../../../../demosplan/DemosPlanCoreBundle/DataFixtures/ORM/TestData'
        public: true
        tags: ['doctrine.fixture.orm']

############### Commands

    demosplan\DemosPlanCoreBundle\Command\:
        resource: '../../../../demosplan/DemosPlanCoreBundle/Command'
        exclude: '../../../../demosplan/DemosPlanCoreBundle/Command/Helpers'
        autowire: true
        tags: ['console.command']

############### Resource Types

    demosplan\DemosPlanCoreBundle\ResourceTypes\:
        resource: '../../../../demosplan/DemosPlanCoreBundle/ResourceTypes'
        autowire: true
        tags: ['dplan.resourceType']

############### Event Subscriber
    demosplan\DemosPlanCoreBundle\EventSubscriber\:
        autoconfigure: true
        autowire: true
        resource: '../../../../demosplan/DemosPlanCoreBundle/EventSubscriber'
        tags: ['kernel.event_subscriber']
