<?php

declare(strict_types=1);

/**
 * This file is part of the package demosplan.
 *
 * (c) 2010-present DEMOS plan GmbH, for more information see the license file.
 *
 * All rights reserved
 */

namespace Tests\Core\Export\Unit;

use demosplan\DemosPlanCoreBundle\Entity\Statement\AssessmentTableExportJob;
use demosplan\DemosPlanCoreBundle\Logic\Export\ExportJobStatusWriter;
use Doctrine\DBAL\Connection;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Exception\EntityManagerClosed;
use Doctrine\ORM\Mapping\ClassMetadata;
use Psr\Log\LoggerInterface;
use ReflectionProperty;
use Tests\Base\UnitTestCase;

class ExportJobStatusWriterTest extends UnitTestCase
{
    protected ?ExportJobStatusWriter $sut = null;

    private ?EntityManagerInterface $entityManagerMock = null;
    private ?Connection $connectionMock = null;
    private ?LoggerInterface $loggerMock = null;

    protected function setUp(): void
    {
        parent::setUp();

        $this->connectionMock = $this->createMock(Connection::class);
        $this->entityManagerMock = $this->createMock(EntityManagerInterface::class);
        $this->entityManagerMock->method('getConnection')->willReturn($this->connectionMock);

        $metadata = $this->createMock(ClassMetadata::class);
        $metadata->method('getTableName')->willReturn('assessment_table_export_job');
        $this->entityManagerMock->method('getClassMetadata')->willReturn($metadata);

        $this->loggerMock = $this->createMock(LoggerInterface::class);
        $this->sut = new ExportJobStatusWriter($this->entityManagerMock, $this->loggerMock);
    }

    public function testPersistFlushesWhenEntityManagerIsOpen(): void
    {
        // Arrange
        $this->entityManagerMock->method('isOpen')->willReturn(true);
        $this->entityManagerMock->expects($this->once())->method('flush');
        $this->connectionMock->expects($this->never())->method('executeStatement');

        // Act
        $this->sut->persist($this->failedJob());
    }

    public function testPersistFallsBackToDbalWhenEntityManagerIsClosed(): void
    {
        // Arrange - a Doctrine exception during the export closes the EntityManager. Without the
        // fallback the row would keep its 'processing' status and block the export forever.
        $this->entityManagerMock->method('isOpen')->willReturn(false);
        $this->entityManagerMock->expects($this->never())->method('flush');
        $this->connectionMock->expects($this->once())
            ->method('executeStatement')
            ->with(
                $this->stringContains('UPDATE assessment_table_export_job SET status = :status'),
                $this->callback(static fn (array $parameters): bool => AssessmentTableExportJob::STATUS_FAILED === $parameters['status']
                    && 'job-1' === $parameters['id'])
            );

        // Act
        $this->sut->persist($this->failedJob());
    }

    public function testPersistFallsBackToDbalWhenFlushFails(): void
    {
        // Arrange - the EntityManager reports itself open but the flush itself fails
        $this->entityManagerMock->method('isOpen')->willReturn(true);
        $this->entityManagerMock->method('flush')->willThrowException(EntityManagerClosed::create());
        $this->connectionMock->expects($this->once())->method('executeStatement');

        // Act
        $this->sut->persist($this->failedJob());
    }

    public function testPersistRollsBackAnOpenTransactionFirst(): void
    {
        // Arrange - a transaction left open by the failed export would keep the update from landing
        $this->connectionMock->method('isTransactionActive')->willReturn(true);
        $this->entityManagerMock->method('isOpen')->willReturn(true);
        $this->entityManagerMock->expects($this->once())->method('rollback');

        // Act
        $this->sut->persist($this->failedJob());
    }

    public function testPersistLogsCriticalWhenBothWritesFail(): void
    {
        // Arrange
        $this->entityManagerMock->method('isOpen')->willReturn(false);
        $this->connectionMock->method('executeStatement')->willThrowException(EntityManagerClosed::create());
        $this->loggerMock->expects($this->once())->method('critical');

        // Act - must not throw: the message is already being handled in a finally block
        $this->sut->persist($this->failedJob());
    }

    private function failedJob(): AssessmentTableExportJob
    {
        $job = new AssessmentTableExportJob();
        $job->setStatus(AssessmentTableExportJob::STATUS_FAILED);
        $job->setErrorMessage('translated:error.export');
        // The id is generated by Doctrine, so set it the way a loaded entity would have it.
        $reflectionProperty = new ReflectionProperty(AssessmentTableExportJob::class, 'id');
        $reflectionProperty->setValue($job, 'job-1');

        return $job;
    }
}
