DemosPlanCore_annotations:
    resource: "../../../../DemosPlanCoreBundle/Controller/"
    type: "annotation"
addon_routes:
    resource: 'demosplan\DemosPlanCoreBundle\Addon\AddonRoutingLoader::loadRoutes'
    type: service
