<?php

declare(strict_types=1);

/**
 * This file is part of the package demosplan.
 *
 * (c) 2010-present DEMOS plan GmbH, for more information see the license file.
 *
 * All rights reserved
 */

namespace demosplan\DemosPlanCoreBundle\ResourceConfigBuilder;

use demosplan\DemosPlanCoreBundle\Entity\Procedure\ProcedureSubscription;
use demosplan\DemosPlanCoreBundle\Entity\User\User;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ProcedureSubscription>
 *
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureSubscription> $ident {@link ProcedureSubscription::ident}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ProcedureSubscription,User> $user {@link ProcedureSubscription::user}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureSubscription> $userEmail {@link ProcedureSubscription::userEmail}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureSubscription> $postcode {@link ProcedureSubscription::postcode}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureSubscription> $city {@link ProcedureSubscription::city}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureSubscription> $distance {@link ProcedureSubscription::distance}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureSubscription> $deleted {@link ProcedureSubscription::deleted}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureSubscription> $createdDate {@link ProcedureSubscription::createdDate}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureSubscription> $modifiedDate {@link ProcedureSubscription::modifiedDate}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureSubscription> $deletedDate {@link ProcedureSubscription::deletedDate}
 */
class BaseProcedureSubscriptionResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
