<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\ResourceConfigBuilder;

use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;
use demosplan\DemosPlanCoreBundle\Entity\ManualListSort;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ManualListSort>
 *
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ManualListSort> $pId {@link ManualListSort::pId}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ManualListSort> $context {@link ManualListSort::context}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ManualListSort> $namespace {@link ManualListSort::namespace}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ManualListSort> $idents {@link ManualListSort::idents}
 */
class BaseManualListSortResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
