<?php

declare(strict_types=1);

/**
 * This file is part of the package demosplan.
 *
 * (c) 2010-present DEMOS plan GmbH, for more information see the license file.
 *
 * All rights reserved
 */

namespace demosplan\DemosPlanCoreBundle\ResourceConfigBuilder;

use demosplan\DemosPlanCoreBundle\Entity\Faq;
use demosplan\DemosPlanCoreBundle\Entity\FaqCategory;
use demosplan\DemosPlanCoreBundle\Entity\User\Role;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToManyRelationshipConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Faq>
 *
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Faq> $title {@link Faq::title}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Faq> $text {@link Faq::text}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Faq> $enabled {@link Faq::enabled}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Faq> $createDate {@link Faq::createDate}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Faq> $modifyDate {@link Faq::modifyDate}
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Faq,Role> $roles {@link Faq::roles}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Faq,FaqCategory> $faqCategory {@link Faq::faqCategory}
 */
class BaseFaqResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
