<?php

declare(strict_types=1);

/**
 * This file is part of the package demosplan.
 *
 * (c) 2010-present DEMOS plan GmbH, for more information see the license file.
 *
 * All rights reserved
 */

namespace demosplan\DemosPlanCoreBundle\ResourceConfigBuilder;

use demosplan\DemosPlanCoreBundle\Entity\Branding;
use demosplan\DemosPlanCoreBundle\Entity\Procedure\Procedure;
use demosplan\DemosPlanCoreBundle\Entity\Slug;
use demosplan\DemosPlanCoreBundle\Entity\User\Address;
use demosplan\DemosPlanCoreBundle\Entity\User\AddressBookEntry;
use demosplan\DemosPlanCoreBundle\Entity\User\Department;
use demosplan\DemosPlanCoreBundle\Entity\User\InstitutionTag;
use demosplan\DemosPlanCoreBundle\Entity\User\MasterToeb;
use demosplan\DemosPlanCoreBundle\Entity\User\Orga;
use demosplan\DemosPlanCoreBundle\Entity\User\OrgaStatusInCustomer;
use demosplan\DemosPlanCoreBundle\Entity\User\User;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToManyRelationshipConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Orga>
 *
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Orga> $name {@link Orga::name}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Orga> $gatewayName {@link Orga::gatewayName}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Orga> $code {@link Orga::code}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Orga> $createdDate {@link Orga::createdDate}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Orga> $modifiedDate {@link Orga::modifiedDate}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Orga> $ccEmail2 {@link Orga::ccEmail2}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Orga> $emailReviewerAdmin {@link Orga::emailReviewerAdmin}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Orga> $deleted {@link Orga::deleted}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Orga> $showname {@link Orga::showname}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Orga> $showlist {@link Orga::showlist}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Orga> $gwId {@link Orga::gwId}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Orga> $competence {@link Orga::competence}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Orga> $email2 {@link Orga::email2}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Orga> $contactPerson {@link Orga::contactPerson}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Orga> $paperCopy {@link Orga::paperCopy}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Orga> $paperCopySpec {@link Orga::paperCopySpec}
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Orga,Address> $addresses {@link Orga::addresses}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Orga> $dataProtection {@link Orga::dataProtection}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Orga> $imprint {@link Orga::imprint}
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Orga,User> $users {@link Orga::users}
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Orga,Department> $departments {@link Orga::departments}
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Orga,Procedure> $procedures {@link Orga::procedures}
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Orga,Procedure> $procedureInvitations {@link Orga::procedureInvitations}
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Orga,AddressBookEntry> $addressBookEntries {@link Orga::addressBookEntries}
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Orga,OrgaStatusInCustomer> $statusInCustomers {@link Orga::statusInCustomers}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Orga,MasterToeb> $masterToeb {@link Orga::masterToeb}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Orga,Branding> $branding {@link Orga::branding}
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Orga,Procedure> $administratableProcedures {@link Orga::administratableProcedures}
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Orga,InstitutionTag> $assignedTags {@link Orga::assignedTags}
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Orga,InstitutionTag> $ownInstitutionTags {@link Orga::ownInstitutionTags}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Orga,Slug> $currentSlug {@link Orga::currentSlug}
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Orga,Slug> $slugs {@link Orga::slugs}
 */
class BaseOrgaResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
