<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\ResourceConfigBuilder;

use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToManyRelationshipConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;
use demosplan\DemosPlanCoreBundle\Entity\Procedure\Procedure;
use demosplan\DemosPlanCoreBundle\Entity\Survey\Survey;
use demosplan\DemosPlanCoreBundle\Entity\Survey\SurveyVote;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Survey>
 *
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Survey> $title {@link Survey::title}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Survey> $description {@link Survey::description}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Survey> $startDate {@link Survey::startDate}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Survey> $endDate {@link Survey::endDate}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Survey> $status {@link Survey::status}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Survey,Procedure> $procedure {@link Survey::procedure}
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Survey,SurveyVote> $votes {@link Survey::votes}
 */
class BaseSurveyResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
