<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\ResourceConfigBuilder;

use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;
use demosplan\DemosPlanCoreBundle\Entity\File;
use demosplan\DemosPlanCoreBundle\Entity\Procedure\Procedure;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,File>
 *
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,File> $ident {@link File::ident}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,File> $hash {@link File::hash}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,File> $name {@link File::name}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,File> $description {@link File::description}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,File> $path {@link File::path}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,File> $filename {@link File::filename}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,File> $tags {@link File::tags}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,File> $author {@link File::author}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,File> $application {@link File::application}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,File> $mimetype {@link File::mimetype}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,File> $created {@link File::created}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,File> $modified {@link File::modified}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,File> $validUntil {@link File::validUntil}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,File> $deleted {@link File::deleted}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,File> $statDown {@link File::statDown}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,File> $infected {@link File::infected}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,File> $lastVScan {@link File::lastVScan}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,File> $blocked {@link File::blocked}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,File> $size {@link File::size}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,File,Procedure> $procedure {@link File::procedure}
 */
class BaseFileResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
