<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\ResourceConfigBuilder;

use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;
use demosplan\DemosPlanCoreBundle\Entity\Report\ReportEntry;
use demosplan\DemosPlanCoreBundle\Entity\User\Customer;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ReportEntry>
 *
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ReportEntry> $category {@link ReportEntry::category}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ReportEntry> $group {@link ReportEntry::group}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ReportEntry> $level {@link ReportEntry::level}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ReportEntry> $userId {@link ReportEntry::userId}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ReportEntry> $userName {@link ReportEntry::userName}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ReportEntry> $sessionId {@link ReportEntry::sessionId}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ReportEntry> $identifierType {@link ReportEntry::identifierType}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ReportEntry> $identifier {@link ReportEntry::identifier}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ReportEntry> $mimeType {@link ReportEntry::mimeType}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ReportEntry> $message {@link ReportEntry::message}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ReportEntry> $incoming {@link ReportEntry::incoming}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ReportEntry> $createDate {@link ReportEntry::createDate}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ReportEntry,Customer> $customer {@link ReportEntry::customer}
 */
class BaseReportEntryResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
