<?php

declare(strict_types=1);

/**
 * This file is part of the package demosplan.
 *
 * (c) 2010-present DEMOS plan GmbH, for more information see the license file.
 *
 * All rights reserved
 */

namespace demosplan\DemosPlanCoreBundle\ResourceConfigBuilder;

use demosplan\DemosPlanCoreBundle\Entity\User\Department;
use demosplan\DemosPlanCoreBundle\Entity\User\MasterToeb;
use demosplan\DemosPlanCoreBundle\Entity\User\Orga;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,MasterToeb>
 *
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,MasterToeb> $ident {@link MasterToeb::ident}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,MasterToeb> $gatewayGroup {@link MasterToeb::gatewayGroup}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,MasterToeb> $orgaName {@link MasterToeb::orgaName}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,MasterToeb,Orga> $orga {@link MasterToeb::orga}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,MasterToeb> $oId {@link MasterToeb::oId}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,MasterToeb,Department> $department {@link MasterToeb::department}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,MasterToeb> $departmentName {@link MasterToeb::departmentName}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,MasterToeb> $sign {@link MasterToeb::sign}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,MasterToeb> $email {@link MasterToeb::email}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,MasterToeb> $ccEmail {@link MasterToeb::ccEmail}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,MasterToeb> $contactPerson {@link MasterToeb::contactPerson}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,MasterToeb> $memo {@link MasterToeb::memo}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,MasterToeb> $comment {@link MasterToeb::comment}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,MasterToeb> $registered {@link MasterToeb::registered}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,MasterToeb> $districtHHMitte {@link MasterToeb::districtHHMitte}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,MasterToeb> $districtEimsbuettel {@link MasterToeb::districtEimsbuettel}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,MasterToeb> $districtAltona {@link MasterToeb::districtAltona}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,MasterToeb> $districtHHNord {@link MasterToeb::districtHHNord}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,MasterToeb> $districtWandsbek {@link MasterToeb::districtWandsbek}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,MasterToeb> $districtBergedorf {@link MasterToeb::districtBergedorf}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,MasterToeb> $districtHarburg {@link MasterToeb::districtHarburg}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,MasterToeb> $districtBsu {@link MasterToeb::districtBsu}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,MasterToeb> $documentRoughAgreement {@link MasterToeb::documentRoughAgreement}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,MasterToeb> $documentAgreement {@link MasterToeb::documentAgreement}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,MasterToeb> $documentNotice {@link MasterToeb::documentNotice}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,MasterToeb> $documentAssessment {@link MasterToeb::documentAssessment}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,MasterToeb> $createdDate {@link MasterToeb::createdDate}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,MasterToeb> $modifiedDate {@link MasterToeb::modifiedDate}
 */
class BaseMasterToebResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
