<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\ResourceConfigBuilder;

use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;
use demosplan\DemosPlanCoreBundle\Entity\Document\ParagraphVersion;
use demosplan\DemosPlanCoreBundle\Entity\Document\SingleDocumentVersion;
use demosplan\DemosPlanCoreBundle\Entity\Procedure\Procedure;
use demosplan\DemosPlanCoreBundle\Entity\Statement\StatementFragment;
use demosplan\DemosPlanCoreBundle\Entity\Statement\StatementFragmentVersion;
use demosplan\DemosPlanCoreBundle\Entity\User\Department;
use demosplan\DemosPlanCoreBundle\Entity\User\User;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,StatementFragmentVersion>
 *
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,StatementFragmentVersion,StatementFragment> $statementFragment {@link StatementFragmentVersion::statementFragment}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementFragmentVersion> $displayId {@link StatementFragmentVersion::displayId}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementFragmentVersion> $text {@link StatementFragmentVersion::text}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementFragmentVersion> $tagAndTopicNames {@link StatementFragmentVersion::tagAndTopicNames}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,StatementFragmentVersion,Procedure> $procedure {@link StatementFragmentVersion::procedure}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementFragmentVersion> $voteAdvice {@link StatementFragmentVersion::voteAdvice}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementFragmentVersion> $vote {@link StatementFragmentVersion::vote}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementFragmentVersion> $created {@link StatementFragmentVersion::created}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementFragmentVersion> $departmentName {@link StatementFragmentVersion::departmentName}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementFragmentVersion> $orgaName {@link StatementFragmentVersion::orgaName}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementFragmentVersion> $considerationAdvice {@link StatementFragmentVersion::considerationAdvice}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementFragmentVersion> $consideration {@link StatementFragmentVersion::consideration}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementFragmentVersion> $countyNames {@link StatementFragmentVersion::countyNames}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementFragmentVersion> $priorityAreaKeys {@link StatementFragmentVersion::priorityAreaKeys}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementFragmentVersion> $municipalityNames {@link StatementFragmentVersion::municipalityNames}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementFragmentVersion> $archivedOrgaName {@link StatementFragmentVersion::archivedOrgaName}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementFragmentVersion> $archivedDepartmentName {@link StatementFragmentVersion::archivedDepartmentName}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementFragmentVersion> $archivedVoteUserName {@link StatementFragmentVersion::archivedVoteUserName}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,StatementFragmentVersion,User> $modifiedByUser {@link StatementFragmentVersion::modifiedByUser}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,StatementFragmentVersion,Department> $modifiedByDepartment {@link StatementFragmentVersion::modifiedByDepartment}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementFragmentVersion> $elementTitle {@link StatementFragmentVersion::elementTitle}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementFragmentVersion> $elementCategory {@link StatementFragmentVersion::elementCategory}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,StatementFragmentVersion,ParagraphVersion> $paragraph {@link StatementFragmentVersion::paragraph}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,StatementFragmentVersion,SingleDocumentVersion> $document {@link StatementFragmentVersion::document}
 */
class BaseStatementFragmentVersionResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
