<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\ResourceConfigBuilder;

use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;
use demosplan\DemosPlanCoreBundle\Entity\OpenGeoDbShortTable;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,OpenGeoDbShortTable>
 *
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,OpenGeoDbShortTable> $uniqueId {@link OpenGeoDbShortTable::uniqueId}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,OpenGeoDbShortTable> $postcode {@link OpenGeoDbShortTable::postcode}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,OpenGeoDbShortTable> $city {@link OpenGeoDbShortTable::city}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,OpenGeoDbShortTable> $municipalCode {@link OpenGeoDbShortTable::municipalCode}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,OpenGeoDbShortTable> $state {@link OpenGeoDbShortTable::state}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,OpenGeoDbShortTable> $lat {@link OpenGeoDbShortTable::lat}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,OpenGeoDbShortTable> $lon {@link OpenGeoDbShortTable::lon}
 */
class BaseOpenGeoDbShortTableResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
