<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\ResourceConfigBuilder;

use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;
use demosplan\DemosPlanCoreBundle\Entity\Statement\Statement;
use demosplan\DemosPlanCoreBundle\Entity\Statement\StatementVersionField;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,StatementVersionField>
 *
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementVersionField> $userIdent {@link StatementVersionField::userIdent}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementVersionField> $userName {@link StatementVersionField::userName}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementVersionField> $sessionIdent {@link StatementVersionField::sessionIdent}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementVersionField> $name {@link StatementVersionField::name}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementVersionField> $type {@link StatementVersionField::type}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementVersionField> $value {@link StatementVersionField::value}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementVersionField> $created {@link StatementVersionField::created}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,StatementVersionField,Statement> $statement {@link StatementVersionField::statement}
 */
class BaseStatementVersionFieldResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
