<?php

declare(strict_types=1);

/**
 * This file is part of the package demosplan.
 *
 * (c) 2010-present DEMOS plan GmbH, for more information see the license file.
 *
 * All rights reserved
 */

namespace demosplan\DemosPlanCoreBundle\ResourceConfigBuilder;

use demosplan\DemosPlanCoreBundle\Entity\File;
use demosplan\DemosPlanCoreBundle\Entity\Procedure\ProcedureProposal;
use demosplan\DemosPlanCoreBundle\Entity\User\User;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToManyRelationshipConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ProcedureProposal>
 *
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureProposal> $name {@link ProcedureProposal::name}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureProposal> $description {@link ProcedureProposal::description}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureProposal> $createdDate {@link ProcedureProposal::createdDate}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureProposal> $modifiedDate {@link ProcedureProposal::modifiedDate}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureProposal> $additionalExplanation {@link ProcedureProposal::additionalExplanation}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureProposal> $coordinate {@link ProcedureProposal::coordinate}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ProcedureProposal,User> $user {@link ProcedureProposal::user}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureProposal> $status {@link ProcedureProposal::status}
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ProcedureProposal,File> $files {@link ProcedureProposal::files}
 */
class BaseProcedureProposalResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
