<?php

declare(strict_types=1);

/**
 * This file is part of the package demosplan.
 *
 * (c) 2010-present DEMOS plan GmbH, for more information see the license file.
 *
 * All rights reserved
 */

namespace demosplan\DemosPlanCoreBundle\ResourceConfigBuilder;

use demosplan\DemosPlanCoreBundle\Entity\Statement\Statement;
use demosplan\DemosPlanCoreBundle\Entity\Statement\StatementVote;
use demosplan\DemosPlanCoreBundle\Entity\User\User;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,StatementVote>
 *
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,StatementVote,Statement> $statement {@link StatementVote::statement}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,StatementVote,User> $user {@link StatementVote::user}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementVote> $firstName {@link StatementVote::firstName}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementVote> $lastName {@link StatementVote::lastName}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementVote> $active {@link StatementVote::active}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementVote> $deleted {@link StatementVote::deleted}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementVote> $createdDate {@link StatementVote::createdDate}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementVote> $modifiedDate {@link StatementVote::modifiedDate}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementVote> $deletedDate {@link StatementVote::deletedDate}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementVote> $manual {@link StatementVote::manual}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementVote> $createdByCitizen {@link StatementVote::createdByCitizen}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementVote> $organisationName {@link StatementVote::organisationName}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementVote> $departmentName {@link StatementVote::departmentName}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementVote> $userName {@link StatementVote::userName}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementVote> $userMail {@link StatementVote::userMail}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementVote> $userPostcode {@link StatementVote::userPostcode}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementVote> $userCity {@link StatementVote::userCity}
 */
class BaseStatementVoteResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
