<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\ResourceConfigBuilder;

use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToManyRelationshipConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;
use demosplan\DemosPlanCoreBundle\Entity\Document\Elements;
use demosplan\DemosPlanCoreBundle\Entity\Document\Paragraph;
use demosplan\DemosPlanCoreBundle\Entity\Document\ParagraphVersion;
use demosplan\DemosPlanCoreBundle\Entity\Procedure\Procedure;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Paragraph>
 *
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Paragraph,Procedure> $procedure {@link Paragraph::procedure}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Paragraph,Paragraph> $parent {@link Paragraph::parent}
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Paragraph,Paragraph> $children {@link Paragraph::children}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Paragraph,Elements> $element {@link Paragraph::element}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Paragraph> $category {@link Paragraph::category}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Paragraph> $title {@link Paragraph::title}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Paragraph> $text {@link Paragraph::text}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Paragraph> $order {@link Paragraph::order}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Paragraph> $visible {@link Paragraph::visible}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Paragraph> $deleted {@link Paragraph::deleted}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Paragraph> $lockReason {@link Paragraph::lockReason}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Paragraph> $createDate {@link Paragraph::createDate}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Paragraph> $modifyDate {@link Paragraph::modifyDate}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Paragraph> $deleteDate {@link Paragraph::deleteDate}
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Paragraph,ParagraphVersion> $versions {@link Paragraph::versions}
 */
class BaseParagraphResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
