<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\ResourceConfigBuilder;

use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;
use demosplan\DemosPlanCoreBundle\Entity\Procedure\Procedure;
use demosplan\DemosPlanCoreBundle\Entity\Workflow\Place;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Place>
 *
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Place> $description {@link Place::description}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Place,Procedure> $procedure {@link Place::procedure}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Place> $name {@link Place::name}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Place> $sortIndex {@link Place::sortIndex}
 */
class BasePlaceResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
