<?php

declare(strict_types=1);

/**
 * This file is part of the package demosplan.
 *
 * (c) 2010-present DEMOS plan GmbH, for more information see the license file.
 *
 * All rights reserved
 */

namespace demosplan\DemosPlanCoreBundle\ResourceConfigBuilder;

use demosplan\DemosPlanCoreBundle\Entity\Procedure\Boilerplate;
use demosplan\DemosPlanCoreBundle\Entity\Procedure\BoilerplateCategory;
use demosplan\DemosPlanCoreBundle\Entity\Procedure\BoilerplateGroup;
use demosplan\DemosPlanCoreBundle\Entity\Procedure\Procedure;
use demosplan\DemosPlanCoreBundle\Entity\Statement\Tag;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToManyRelationshipConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Boilerplate>
 *
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Boilerplate> $ident {@link Boilerplate::ident}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Boilerplate,Procedure> $procedure {@link Boilerplate::procedure}
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Boilerplate,BoilerplateCategory> $categories {@link Boilerplate::categories}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Boilerplate,BoilerplateGroup> $group {@link Boilerplate::group}
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Boilerplate,Tag> $tags {@link Boilerplate::tags}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Boilerplate> $title {@link Boilerplate::title}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Boilerplate> $text {@link Boilerplate::text}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Boilerplate> $createDate {@link Boilerplate::createDate}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Boilerplate> $modifyDate {@link Boilerplate::modifyDate}
 */
class BaseBoilerplateResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
