<?php

declare(strict_types=1);

/**
 * This file is part of the package demosplan.
 *
 * (c) 2010-present DEMOS plan GmbH, for more information see the license file.
 *
 * All rights reserved
 */

namespace demosplan\DemosPlanCoreBundle\ResourceConfigBuilder;

use demosplan\DemosPlanCoreBundle\Entity\Sessions;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Sessions>
 *
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Sessions> $sess_id {@link Sessions::sess_id}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Sessions> $sess_data {@link Sessions::sess_data}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Sessions> $sess_lifetime {@link Sessions::sess_lifetime}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Sessions> $sess_time {@link Sessions::sess_time}
 */
class BaseSessionsResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
