<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\ResourceConfigBuilder;

use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;
use demosplan\DemosPlanCoreBundle\Entity\MailTemplate;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,MailTemplate>
 *
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,MailTemplate> $label {@link MailTemplate::label}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,MailTemplate> $language {@link MailTemplate::language}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,MailTemplate> $title {@link MailTemplate::title}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,MailTemplate> $content {@link MailTemplate::content}
 */
class BaseMailTemplateResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
