<?php

declare(strict_types=1);

/**
 * This file is part of the package demosplan.
 *
 * (c) 2010-present DEMOS plan GmbH, for more information see the license file.
 *
 * All rights reserved
 */

namespace demosplan\DemosPlanCoreBundle\ResourceConfigBuilder;

use demosplan\DemosPlanCoreBundle\Entity\Survey\Survey;
use demosplan\DemosPlanCoreBundle\Entity\Survey\SurveyVote;
use demosplan\DemosPlanCoreBundle\Entity\User\User;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,SurveyVote>
 *
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,SurveyVote> $isAgreed {@link SurveyVote::isAgreed}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,SurveyVote> $text {@link SurveyVote::text}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,SurveyVote> $textReview {@link SurveyVote::textReview}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,SurveyVote> $createdDate {@link SurveyVote::createdDate}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,SurveyVote,Survey> $survey {@link SurveyVote::survey}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,SurveyVote,User> $user {@link SurveyVote::user}
 */
class BaseSurveyVoteResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
