<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\ResourceConfigBuilder;

use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;
use demosplan\DemosPlanCoreBundle\Entity\Statement\Statement;
use demosplan\DemosPlanCoreBundle\Entity\Statement\StatementMeta;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,StatementMeta>
 *
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,StatementMeta,Statement> $statement {@link StatementMeta::statement}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementMeta> $authorName {@link StatementMeta::authorName}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementMeta> $authorFeedback {@link StatementMeta::authorFeedback}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementMeta> $submitUId {@link StatementMeta::submitUId}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementMeta> $submitName {@link StatementMeta::submitName}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementMeta> $orgaName {@link StatementMeta::orgaName}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementMeta> $orgaDepartmentName {@link StatementMeta::orgaDepartmentName}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementMeta> $caseWorkerName {@link StatementMeta::caseWorkerName}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementMeta> $orgaStreet {@link StatementMeta::orgaStreet}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementMeta> $houseNumber {@link StatementMeta::houseNumber}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementMeta> $orgaPostalCode {@link StatementMeta::orgaPostalCode}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementMeta> $orgaCity {@link StatementMeta::orgaCity}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementMeta> $orgaEmail {@link StatementMeta::orgaEmail}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementMeta> $authoredDate {@link StatementMeta::authoredDate}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementMeta> $submitOrgaId {@link StatementMeta::submitOrgaId}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementMeta> $miscData {@link StatementMeta::miscData}
 */
class BaseStatementMetaResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
