<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\ResourceConfigBuilder;

use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;
use demosplan\DemosPlanCoreBundle\Entity\User\Department;
use demosplan\DemosPlanCoreBundle\Entity\User\MasterToeb;
use demosplan\DemosPlanCoreBundle\Entity\User\MasterToebVersion;
use demosplan\DemosPlanCoreBundle\Entity\User\Orga;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,MasterToebVersion>
 *
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,MasterToebVersion> $ident {@link MasterToebVersion::ident}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,MasterToebVersion,MasterToeb> $masterToeb {@link MasterToebVersion::masterToeb}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,MasterToebVersion> $gatewayGroup {@link MasterToebVersion::gatewayGroup}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,MasterToebVersion> $orgaName {@link MasterToebVersion::orgaName}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,MasterToebVersion,Orga> $orga {@link MasterToebVersion::orga}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,MasterToebVersion,Department> $department {@link MasterToebVersion::department}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,MasterToebVersion> $departmentName {@link MasterToebVersion::departmentName}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,MasterToebVersion> $sign {@link MasterToebVersion::sign}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,MasterToebVersion> $email {@link MasterToebVersion::email}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,MasterToebVersion> $ccEmail {@link MasterToebVersion::ccEmail}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,MasterToebVersion> $contactPerson {@link MasterToebVersion::contactPerson}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,MasterToebVersion> $memo {@link MasterToebVersion::memo}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,MasterToebVersion> $comment {@link MasterToebVersion::comment}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,MasterToebVersion> $registered {@link MasterToebVersion::registered}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,MasterToebVersion> $districtHHMitte {@link MasterToebVersion::districtHHMitte}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,MasterToebVersion> $districtEimsbuettel {@link MasterToebVersion::districtEimsbuettel}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,MasterToebVersion> $districtAltona {@link MasterToebVersion::districtAltona}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,MasterToebVersion> $districtHHNord {@link MasterToebVersion::districtHHNord}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,MasterToebVersion> $districtWandsbek {@link MasterToebVersion::districtWandsbek}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,MasterToebVersion> $districtBergedorf {@link MasterToebVersion::districtBergedorf}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,MasterToebVersion> $districtHarburg {@link MasterToebVersion::districtHarburg}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,MasterToebVersion> $districtBsu {@link MasterToebVersion::districtBsu}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,MasterToebVersion> $documentRoughAgreement {@link MasterToebVersion::documentRoughAgreement}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,MasterToebVersion> $documentAgreement {@link MasterToebVersion::documentAgreement}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,MasterToebVersion> $documentNotice {@link MasterToebVersion::documentNotice}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,MasterToebVersion> $documentAssessment {@link MasterToebVersion::documentAssessment}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,MasterToebVersion> $createdDate {@link MasterToebVersion::createdDate}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,MasterToebVersion> $modifiedDate {@link MasterToebVersion::modifiedDate}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,MasterToebVersion> $versionDate {@link MasterToebVersion::versionDate}
 */
class BaseMasterToebVersionResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
