<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\ResourceConfigBuilder;

use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToManyRelationshipConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;
use demosplan\DemosPlanCoreBundle\Entity\Branding;
use demosplan\DemosPlanCoreBundle\Entity\Procedure\Procedure;
use demosplan\DemosPlanCoreBundle\Entity\User\Customer;
use demosplan\DemosPlanCoreBundle\Entity\User\CustomerCounty;
use demosplan\DemosPlanCoreBundle\Entity\User\OrgaStatusInCustomer;
use demosplan\DemosPlanCoreBundle\Entity\User\SupportContact;
use demosplan\DemosPlanCoreBundle\Entity\User\UserRoleInCustomer;
use demosplan\DemosPlanCoreBundle\Entity\Video;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Customer>
 *
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Customer,CustomerCounty> $customerCounties {@link Customer::customerCounties}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Customer> $imprint {@link Customer::imprint}
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Customer,UserRoleInCustomer> $userRoles {@link Customer::userRoles}
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Customer,OrgaStatusInCustomer> $orgaStatuses {@link Customer::orgaStatuses}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Customer> $dataProtection {@link Customer::dataProtection}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Customer> $termsOfUse {@link Customer::termsOfUse}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Customer> $xplanning {@link Customer::xplanning}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Customer,Procedure> $defaultProcedureBlueprint {@link Customer::defaultProcedureBlueprint}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Customer> $mapAttribution {@link Customer::mapAttribution}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Customer> $baseLayerUrl {@link Customer::baseLayerUrl}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Customer> $baseLayerLayers {@link Customer::baseLayerLayers}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Customer,Branding> $branding {@link Customer::branding}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Customer> $accessibilityExplanation {@link Customer::accessibilityExplanation}
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Customer,Video> $signLanguageOverviewVideos {@link Customer::signLanguageOverviewVideos}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Customer> $signLanguageOverviewDescription {@link Customer::signLanguageOverviewDescription}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Customer> $overviewDescriptionInSimpleLanguage {@link Customer::overviewDescriptionInSimpleLanguage}
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Customer,SupportContact> $contacts {@link Customer::contacts}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Customer> $name {@link Customer::name}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Customer> $subdomain {@link Customer::subdomain}
 */
class BaseCustomerResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
