<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\ResourceConfigBuilder;

use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;
use demosplan\DemosPlanCoreBundle\Entity\Forum\ForumThread;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ForumThread>
 *
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ForumThread> $ident {@link ForumThread::ident}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ForumThread> $url {@link ForumThread::url}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ForumThread> $closed {@link ForumThread::closed}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ForumThread> $closingReason {@link ForumThread::closingReason}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ForumThread> $progression {@link ForumThread::progression}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ForumThread> $createDate {@link ForumThread::createDate}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ForumThread> $modifyDate {@link ForumThread::modifyDate}
 */
class BaseForumThreadResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
