<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\ResourceConfigBuilder;

use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;
use demosplan\DemosPlanCoreBundle\Entity\Procedure\HashedQuery;
use demosplan\DemosPlanCoreBundle\Entity\Procedure\Procedure;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,HashedQuery>
 *
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,HashedQuery> $hash {@link HashedQuery::hash}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,HashedQuery> $storedQuery {@link HashedQuery::storedQuery}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,HashedQuery> $created {@link HashedQuery::created}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,HashedQuery> $modified {@link HashedQuery::modified}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,HashedQuery,Procedure> $procedure {@link HashedQuery::procedure}
 */
class BaseHashedQueryResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
