<?php

declare(strict_types=1);

/**
 * This file is part of the package demosplan.
 *
 * (c) 2010-present DEMOS plan GmbH, for more information see the license file.
 *
 * All rights reserved
 */

namespace demosplan\DemosPlanCoreBundle\ResourceConfigBuilder;

use demosplan\DemosPlanCoreBundle\Entity\Document\Elements;
use demosplan\DemosPlanCoreBundle\Entity\Document\ParagraphVersion;
use demosplan\DemosPlanCoreBundle\Entity\Document\SingleDocumentVersion;
use demosplan\DemosPlanCoreBundle\Entity\Procedure\Procedure;
use demosplan\DemosPlanCoreBundle\Entity\Statement\County;
use demosplan\DemosPlanCoreBundle\Entity\Statement\Municipality;
use demosplan\DemosPlanCoreBundle\Entity\Statement\PriorityArea;
use demosplan\DemosPlanCoreBundle\Entity\Statement\Statement;
use demosplan\DemosPlanCoreBundle\Entity\Statement\StatementFragment;
use demosplan\DemosPlanCoreBundle\Entity\Statement\StatementFragmentVersion;
use demosplan\DemosPlanCoreBundle\Entity\Statement\Tag;
use demosplan\DemosPlanCoreBundle\Entity\User\Department;
use demosplan\DemosPlanCoreBundle\Entity\User\User;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToManyRelationshipConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,StatementFragment>
 *
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,StatementFragment,Statement> $statement {@link StatementFragment::statement}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementFragment> $displayId {@link StatementFragment::displayId}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementFragment> $text {@link StatementFragment::text}
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,StatementFragment,Tag> $tags {@link StatementFragment::tags}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,StatementFragment,Procedure> $procedure {@link StatementFragment::procedure}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementFragment> $voteAdvice {@link StatementFragment::voteAdvice}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementFragment> $vote {@link StatementFragment::vote}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementFragment> $created {@link StatementFragment::created}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementFragment> $modified {@link StatementFragment::modified}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementFragment> $assignedToFbDate {@link StatementFragment::assignedToFbDate}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,StatementFragment,Department> $department {@link StatementFragment::department}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementFragment> $considerationAdvice {@link StatementFragment::considerationAdvice}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementFragment> $consideration {@link StatementFragment::consideration}
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,StatementFragment,County> $counties {@link StatementFragment::counties}
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,StatementFragment,PriorityArea> $priorityAreas {@link StatementFragment::priorityAreas}
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,StatementFragment,Municipality> $municipalities {@link StatementFragment::municipalities}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,StatementFragment,Department> $archivedDepartment {@link StatementFragment::archivedDepartment}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementFragment> $archivedOrgaName {@link StatementFragment::archivedOrgaName}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementFragment> $archivedDepartmentName {@link StatementFragment::archivedDepartmentName}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementFragment> $archivedVoteUserName {@link StatementFragment::archivedVoteUserName}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,StatementFragment,User> $assignee {@link StatementFragment::assignee}
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,StatementFragment,StatementFragmentVersion> $versions {@link StatementFragment::versions}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementFragment> $sortIndex {@link StatementFragment::sortIndex}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,StatementFragment,User> $modifiedByUser {@link StatementFragment::modifiedByUser}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,StatementFragment,Department> $modifiedByDepartment {@link StatementFragment::modifiedByDepartment}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementFragment> $status {@link StatementFragment::status}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,StatementFragment,User> $lastClaimed {@link StatementFragment::lastClaimed}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,StatementFragment,Elements> $element {@link StatementFragment::element}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,StatementFragment,ParagraphVersion> $paragraph {@link StatementFragment::paragraph}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,StatementFragment,SingleDocumentVersion> $document {@link StatementFragment::document}
 */
class BaseStatementFragmentResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
