<?php

declare(strict_types=1);

/**
 * This file is part of the package demosplan.
 *
 * (c) 2010-present DEMOS plan GmbH, for more information see the license file.
 *
 * All rights reserved
 */

namespace demosplan\DemosPlanCoreBundle\ResourceConfigBuilder;

use demosplan\DemosPlanCoreBundle\Entity\Forum\DevelopmentRelease;
use demosplan\DemosPlanCoreBundle\Entity\Forum\DevelopmentUserStory;
use demosplan\DemosPlanCoreBundle\Entity\Forum\ForumThread;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,DevelopmentUserStory>
 *
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DevelopmentUserStory> $ident {@link DevelopmentUserStory::ident}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,DevelopmentUserStory,DevelopmentRelease> $release {@link DevelopmentUserStory::release}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,DevelopmentUserStory,ForumThread> $thread {@link DevelopmentUserStory::thread}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DevelopmentUserStory> $onlineVotes {@link DevelopmentUserStory::onlineVotes}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DevelopmentUserStory> $offlineVotes {@link DevelopmentUserStory::offlineVotes}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DevelopmentUserStory> $description {@link DevelopmentUserStory::description}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DevelopmentUserStory> $title {@link DevelopmentUserStory::title}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DevelopmentUserStory> $modifiedDate {@link DevelopmentUserStory::modifiedDate}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DevelopmentUserStory> $createDate {@link DevelopmentUserStory::createDate}
 */
class BaseDevelopmentUserStoryResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
