<?php

declare(strict_types=1);

/**
 * This file is part of the package demosplan.
 *
 * (c) 2010-present DEMOS plan GmbH, for more information see the license file.
 *
 * All rights reserved
 */

namespace demosplan\DemosPlanCoreBundle\ResourceConfigBuilder;

use demosplan\DemosPlanCoreBundle\Entity\Procedure\Procedure;
use demosplan\DemosPlanCoreBundle\Entity\Setting;
use demosplan\DemosPlanCoreBundle\Entity\User\Orga;
use demosplan\DemosPlanCoreBundle\Entity\User\User;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Setting>
 *
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Setting> $ident {@link Setting::ident}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Setting,Procedure> $procedure {@link Setting::procedure}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Setting,User> $user {@link Setting::user}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Setting,Orga> $orga {@link Setting::orga}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Setting> $orgaId {@link Setting::orgaId}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Setting> $key {@link Setting::key}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Setting> $content {@link Setting::content}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Setting> $created {@link Setting::created}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Setting> $modified {@link Setting::modified}
 */
class BaseSettingResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
