<?php

declare(strict_types=1);

/**
 * This file is part of the package demosplan.
 *
 * (c) 2010-present DEMOS plan GmbH, for more information see the license file.
 *
 * All rights reserved
 */

namespace demosplan\DemosPlanCoreBundle\ResourceConfigBuilder;

use demosplan\DemosPlanCoreBundle\Entity\Forum\DevelopmentRelease;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,DevelopmentRelease>
 *
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DevelopmentRelease> $ident {@link DevelopmentRelease::ident}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DevelopmentRelease> $description {@link DevelopmentRelease::description}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DevelopmentRelease> $title {@link DevelopmentRelease::title}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DevelopmentRelease> $phase {@link DevelopmentRelease::phase}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DevelopmentRelease> $startDate {@link DevelopmentRelease::startDate}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DevelopmentRelease> $endDate {@link DevelopmentRelease::endDate}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DevelopmentRelease> $modifiedDate {@link DevelopmentRelease::modifiedDate}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DevelopmentRelease> $createDate {@link DevelopmentRelease::createDate}
 */
class BaseDevelopmentReleaseResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
