<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\ResourceConfigBuilder;

use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToManyRelationshipConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;
use demosplan\DemosPlanCoreBundle\Entity\Procedure\Boilerplate;
use demosplan\DemosPlanCoreBundle\Entity\Procedure\BoilerplateCategory;
use demosplan\DemosPlanCoreBundle\Entity\Procedure\Procedure;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,BoilerplateCategory>
 *
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,BoilerplateCategory,Procedure> $procedure {@link BoilerplateCategory::procedure}
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,BoilerplateCategory,Boilerplate> $boilerplates {@link BoilerplateCategory::boilerplates}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,BoilerplateCategory> $title {@link BoilerplateCategory::title}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,BoilerplateCategory> $description {@link BoilerplateCategory::description}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,BoilerplateCategory> $createDate {@link BoilerplateCategory::createDate}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,BoilerplateCategory> $modifyDate {@link BoilerplateCategory::modifyDate}
 */
class BaseBoilerplateCategoryResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
