<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\ResourceConfigBuilder;

use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;
use demosplan\DemosPlanCoreBundle\Entity\Document\Elements;
use demosplan\DemosPlanCoreBundle\Entity\Document\Paragraph;
use demosplan\DemosPlanCoreBundle\Entity\Document\ParagraphVersion;
use demosplan\DemosPlanCoreBundle\Entity\Procedure\Procedure;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ParagraphVersion>
 *
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ParagraphVersion,Paragraph> $paragraph {@link ParagraphVersion::paragraph}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ParagraphVersion,Procedure> $procedure {@link ParagraphVersion::procedure}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ParagraphVersion,Elements> $element {@link ParagraphVersion::element}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ParagraphVersion> $category {@link ParagraphVersion::category}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ParagraphVersion> $title {@link ParagraphVersion::title}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ParagraphVersion> $text {@link ParagraphVersion::text}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ParagraphVersion> $order {@link ParagraphVersion::order}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ParagraphVersion> $visible {@link ParagraphVersion::visible}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ParagraphVersion> $deleted {@link ParagraphVersion::deleted}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ParagraphVersion> $versionDate {@link ParagraphVersion::versionDate}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ParagraphVersion> $createDate {@link ParagraphVersion::createDate}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ParagraphVersion> $modifyDate {@link ParagraphVersion::modifyDate}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ParagraphVersion> $deleteDate {@link ParagraphVersion::deleteDate}
 */
class BaseParagraphVersionResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
