<?php

declare(strict_types=1);

/**
 * This file is part of the package demosplan.
 *
 * (c) 2010-present DEMOS plan GmbH, for more information see the license file.
 *
 * All rights reserved
 */

namespace demosplan\DemosPlanCoreBundle\ResourceConfigBuilder;

use demosplan\DemosPlanCoreBundle\Entity\File;
use demosplan\DemosPlanCoreBundle\Entity\FileContainer;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,FileContainer>
 *
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,FileContainer> $entityId {@link FileContainer::entityId}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,FileContainer> $entityClass {@link FileContainer::entityClass}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,FileContainer> $entityField {@link FileContainer::entityField}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,FileContainer> $createDate {@link FileContainer::createDate}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,FileContainer> $modifyDate {@link FileContainer::modifyDate}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,FileContainer> $order {@link FileContainer::order}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,FileContainer> $fileString {@link FileContainer::fileString}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,FileContainer,File> $file {@link FileContainer::file}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,FileContainer> $publicAllowed {@link FileContainer::publicAllowed}
 */
class BaseFileContainerResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
