<?php

declare(strict_types=1);

/**
 * This file is part of the package demosplan.
 *
 * (c) 2010-present DEMOS plan GmbH, for more information see the license file.
 *
 * All rights reserved
 */

namespace demosplan\DemosPlanCoreBundle\ResourceConfigBuilder;

use demosplan\DemosPlanCoreBundle\Entity\User\Address;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Address>
 *
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Address> $code {@link Address::code}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Address> $street {@link Address::street}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Address> $street1 {@link Address::street1}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Address> $postalcode {@link Address::postalcode}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Address> $city {@link Address::city}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Address> $region {@link Address::region}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Address> $state {@link Address::state}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Address> $postofficebox {@link Address::postofficebox}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Address> $phone {@link Address::phone}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Address> $fax {@link Address::fax}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Address> $email {@link Address::email}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Address> $url {@link Address::url}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Address> $createdDate {@link Address::createdDate}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Address> $modifiedDate {@link Address::modifiedDate}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Address> $deleted {@link Address::deleted}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Address> $houseNumber {@link Address::houseNumber}
 */
class BaseAddressResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
