<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\ResourceConfigBuilder;

use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;
use demosplan\DemosPlanCoreBundle\Entity\User\AddressBookEntry;
use demosplan\DemosPlanCoreBundle\Entity\User\Orga;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,AddressBookEntry>
 *
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,AddressBookEntry> $name {@link AddressBookEntry::name}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,AddressBookEntry,Orga> $organisation {@link AddressBookEntry::organisation}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,AddressBookEntry> $emailAddress {@link AddressBookEntry::emailAddress}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,AddressBookEntry> $createdDate {@link AddressBookEntry::createdDate}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,AddressBookEntry> $modifiedDate {@link AddressBookEntry::modifiedDate}
 */
class BaseAddressBookEntryResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
