<?php

declare(strict_types=1);

/**
 * This file is part of the package demosplan.
 *
 * (c) 2010-present DEMOS plan GmbH, for more information see the license file.
 *
 * All rights reserved
 */

namespace demosplan\DemosPlanCoreBundle\ResourceConfigBuilder;

use demosplan\DemosPlanCoreBundle\Entity\Procedure\StatementFieldDefinition;
use demosplan\DemosPlanCoreBundle\Entity\Procedure\StatementFormDefinition;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,StatementFieldDefinition>
 *
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementFieldDefinition> $creationDate {@link StatementFieldDefinition::creationDate}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementFieldDefinition> $modificationDate {@link StatementFieldDefinition::modificationDate}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementFieldDefinition> $name {@link StatementFieldDefinition::name}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,StatementFieldDefinition,StatementFormDefinition> $statementFormDefinition {@link StatementFieldDefinition::statementFormDefinition}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementFieldDefinition> $orderNumber {@link StatementFieldDefinition::orderNumber}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementFieldDefinition> $enabled {@link StatementFieldDefinition::enabled}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,StatementFieldDefinition> $required {@link StatementFieldDefinition::required}
 */
class BaseStatementFieldDefinitionResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
