<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\ResourceConfigBuilder;

use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToManyRelationshipConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;
use demosplan\DemosPlanCoreBundle\Entity\Procedure\Procedure;
use demosplan\DemosPlanCoreBundle\Entity\Procedure\ProcedurePerson;
use demosplan\DemosPlanCoreBundle\Entity\Statement\Statement;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ProcedurePerson>
 *
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedurePerson> $streetName {@link ProcedurePerson::streetName}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedurePerson> $streetNumber {@link ProcedurePerson::streetNumber}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedurePerson> $city {@link ProcedurePerson::city}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedurePerson> $postalCode {@link ProcedurePerson::postalCode}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedurePerson> $emailAddress {@link ProcedurePerson::emailAddress}
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ProcedurePerson,Statement> $similarForeignStatements {@link ProcedurePerson::similarForeignStatements}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedurePerson> $fullName {@link ProcedurePerson::fullName}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ProcedurePerson,Procedure> $procedure {@link ProcedurePerson::procedure}
 */
class BaseProcedurePersonResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
