<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\ResourceConfigBuilder;

use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToManyRelationshipConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;
use demosplan\DemosPlanCoreBundle\Entity\User\InstitutionTag;
use demosplan\DemosPlanCoreBundle\Entity\User\Orga;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,InstitutionTag>
 *
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,InstitutionTag> $label {@link InstitutionTag::label}
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,InstitutionTag,Orga> $taggedInstitutions {@link InstitutionTag::taggedInstitutions}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,InstitutionTag,Orga> $owningOrganisation {@link InstitutionTag::owningOrganisation}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,InstitutionTag> $creationDate {@link InstitutionTag::creationDate}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,InstitutionTag> $modificationDate {@link InstitutionTag::modificationDate}
 */
class BaseInstitutionTagResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
