<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\ResourceConfigBuilder;

use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;
use demosplan\DemosPlanCoreBundle\Entity\EntityContentChange;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,EntityContentChange>
 *
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,EntityContentChange> $created {@link EntityContentChange::created}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,EntityContentChange> $modified {@link EntityContentChange::modified}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,EntityContentChange> $userId {@link EntityContentChange::userId}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,EntityContentChange> $userName {@link EntityContentChange::userName}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,EntityContentChange> $entityType {@link EntityContentChange::entityType}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,EntityContentChange> $entityId {@link EntityContentChange::entityId}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,EntityContentChange> $entityField {@link EntityContentChange::entityField}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,EntityContentChange> $preUpdate {@link EntityContentChange::preUpdate}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,EntityContentChange> $postUpdate {@link EntityContentChange::postUpdate}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,EntityContentChange> $contentChange {@link EntityContentChange::contentChange}
 */
class BaseEntityContentChangeResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
