<?php

declare(strict_types=1);

/**
 * This file is part of the package demosplan.
 *
 * (c) 2010-present DEMOS plan GmbH, for more information see the license file.
 *
 * All rights reserved
 */

namespace demosplan\DemosPlanCoreBundle\ResourceConfigBuilder;

use demosplan\DemosPlanCoreBundle\Entity\Procedure\Procedure;
use demosplan\DemosPlanCoreBundle\Entity\Procedure\ProcedureType;
use demosplan\DemosPlanCoreBundle\Entity\Procedure\ProcedureUiDefinition;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ProcedureUiDefinition>
 *
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureUiDefinition> $creationDate {@link ProcedureUiDefinition::creationDate}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureUiDefinition> $modificationDate {@link ProcedureUiDefinition::modificationDate}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ProcedureUiDefinition,Procedure> $procedure {@link ProcedureUiDefinition::procedure}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ProcedureUiDefinition,ProcedureType> $procedureType {@link ProcedureUiDefinition::procedureType}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureUiDefinition> $mapHintDefault {@link ProcedureUiDefinition::mapHintDefault}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureUiDefinition> $statementFormHintStatement {@link ProcedureUiDefinition::statementFormHintStatement}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureUiDefinition> $statementFormHintPersonalData {@link ProcedureUiDefinition::statementFormHintPersonalData}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureUiDefinition> $statementFormHintRecheck {@link ProcedureUiDefinition::statementFormHintRecheck}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ProcedureUiDefinition> $statementPublicSubmitConfirmationText {@link ProcedureUiDefinition::statementPublicSubmitConfirmationText}
 */
class BaseProcedureUiDefinitionResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
