<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\ResourceConfigBuilder;

use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;
use demosplan\DemosPlanCoreBundle\Entity\Forum\ForumEntry;
use demosplan\DemosPlanCoreBundle\Entity\Forum\ForumThread;
use demosplan\DemosPlanCoreBundle\Entity\User\User;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ForumEntry>
 *
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ForumEntry> $ident {@link ForumEntry::ident}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ForumEntry,ForumThread> $thread {@link ForumEntry::thread}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,ForumEntry,User> $user {@link ForumEntry::user}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ForumEntry> $userRoles {@link ForumEntry::userRoles}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ForumEntry> $text {@link ForumEntry::text}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ForumEntry> $initialEntry {@link ForumEntry::initialEntry}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ForumEntry> $createDate {@link ForumEntry::createDate}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,ForumEntry> $modifyDate {@link ForumEntry::modifyDate}
 */
class BaseForumEntryResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
