<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\ResourceConfigBuilder;

use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToManyRelationshipConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;
use demosplan\DemosPlanCoreBundle\Entity\Document\Elements;
use demosplan\DemosPlanCoreBundle\Entity\EmailAddress;
use demosplan\DemosPlanCoreBundle\Entity\ExportFieldsConfiguration;
use demosplan\DemosPlanCoreBundle\Entity\File;
use demosplan\DemosPlanCoreBundle\Entity\Procedure\NotificationReceiver;
use demosplan\DemosPlanCoreBundle\Entity\Procedure\Procedure;
use demosplan\DemosPlanCoreBundle\Entity\Procedure\ProcedureBehaviorDefinition;
use demosplan\DemosPlanCoreBundle\Entity\Procedure\ProcedureCategory;
use demosplan\DemosPlanCoreBundle\Entity\Procedure\ProcedureSettings;
use demosplan\DemosPlanCoreBundle\Entity\Procedure\ProcedureType;
use demosplan\DemosPlanCoreBundle\Entity\Procedure\ProcedureUiDefinition;
use demosplan\DemosPlanCoreBundle\Entity\Procedure\StatementFormDefinition;
use demosplan\DemosPlanCoreBundle\Entity\Slug;
use demosplan\DemosPlanCoreBundle\Entity\Statement\Statement;
use demosplan\DemosPlanCoreBundle\Entity\Statement\TagTopic;
use demosplan\DemosPlanCoreBundle\Entity\Survey\Survey;
use demosplan\DemosPlanCoreBundle\Entity\User\Customer;
use demosplan\DemosPlanCoreBundle\Entity\User\Orga;
use demosplan\DemosPlanCoreBundle\Entity\User\User;
use demosplan\DemosPlanCoreBundle\Entity\Workflow\Place;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Procedure>
 *
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Procedure> $name {@link Procedure::name}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Procedure> $shortUrl {@link Procedure::shortUrl}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Procedure> $orgaName {@link Procedure::orgaName}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Procedure,Orga> $orga {@link Procedure::orga}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Procedure> $desc {@link Procedure::desc}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Procedure> $phase {@link Procedure::phase}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Procedure> $step {@link Procedure::step}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Procedure> $logo {@link Procedure::logo}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Procedure> $externId {@link Procedure::externId}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Procedure> $plisId {@link Procedure::plisId}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Procedure> $closed {@link Procedure::closed}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Procedure> $deleted {@link Procedure::deleted}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Procedure> $master {@link Procedure::master}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Procedure> $masterTemplate {@link Procedure::masterTemplate}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Procedure> $externalName {@link Procedure::externalName}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Procedure> $externalDesc {@link Procedure::externalDesc}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Procedure> $publicParticipation {@link Procedure::publicParticipation}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Procedure> $publicParticipationPhase {@link Procedure::publicParticipationPhase}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Procedure> $publicParticipationStep {@link Procedure::publicParticipationStep}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Procedure> $publicParticipationStartDate {@link Procedure::publicParticipationStartDate}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Procedure> $publicParticipationEndDate {@link Procedure::publicParticipationEndDate}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Procedure> $publicParticipationContact {@link Procedure::publicParticipationContact}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Procedure> $publicParticipationPublicationEnabled {@link Procedure::publicParticipationPublicationEnabled}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Procedure> $locationName {@link Procedure::locationName}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Procedure> $locationPostCode {@link Procedure::locationPostCode}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Procedure> $municipalCode {@link Procedure::municipalCode}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Procedure> $ars {@link Procedure::ars}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Procedure> $createdDate {@link Procedure::createdDate}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Procedure> $startDate {@link Procedure::startDate}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Procedure> $endDate {@link Procedure::endDate}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Procedure> $closedDate {@link Procedure::closedDate}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Procedure> $deletedDate {@link Procedure::deletedDate}
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Procedure,Orga> $organisation {@link Procedure::organisation}
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Procedure,Orga> $planningOffices {@link Procedure::planningOffices}
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Procedure,Orga> $dataInputOrganisations {@link Procedure::dataInputOrganisations}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Procedure,ProcedureSettings> $settings {@link Procedure::settings}
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Procedure,TagTopic> $topics {@link Procedure::topics}
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Procedure,NotificationReceiver> $notificationReceivers {@link Procedure::notificationReceivers}
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Procedure,Elements> $elements {@link Procedure::elements}
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Procedure,User> $authorizedUsers {@link Procedure::authorizedUsers}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Procedure> $agencyMainEmailAddress {@link Procedure::agencyMainEmailAddress}
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Procedure,EmailAddress> $agencyExtraEmailAddresses {@link Procedure::agencyExtraEmailAddresses}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Procedure,Customer> $customer {@link Procedure::customer}
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Procedure,ProcedureCategory> $procedureCategories {@link Procedure::procedureCategories}
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Procedure,Statement> $statements {@link Procedure::statements}
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Procedure,Survey> $surveys {@link Procedure::surveys}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Procedure,ProcedureType> $procedureType {@link Procedure::procedureType}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Procedure,StatementFormDefinition> $statementFormDefinition {@link Procedure::statementFormDefinition}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Procedure,ProcedureBehaviorDefinition> $procedureBehaviorDefinition {@link Procedure::procedureBehaviorDefinition}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Procedure,ProcedureUiDefinition> $procedureUiDefinition {@link Procedure::procedureUiDefinition}
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Procedure,ExportFieldsConfiguration> $exportFieldsConfigurations {@link Procedure::exportFieldsConfigurations}
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Procedure,File> $files {@link Procedure::files}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Procedure> $xtaPlanId {@link Procedure::xtaPlanId}
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Procedure,Place> $segmentPlaces {@link Procedure::segmentPlaces}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Procedure,Slug> $currentSlug {@link Procedure::currentSlug}
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Procedure,Slug> $slugs {@link Procedure::slugs}
 */
class BaseProcedureResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
