<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\ResourceConfigBuilder;

use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;
use demosplan\DemosPlanCoreBundle\Entity\Flood;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Flood>
 *
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Flood> $event {@link Flood::event}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Flood> $identifier {@link Flood::identifier}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Flood> $created {@link Flood::created}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Flood> $expires {@link Flood::expires}
 */
class BaseFloodResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
