<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\ResourceConfigBuilder;

use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToManyRelationshipConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;
use demosplan\DemosPlanCoreBundle\Entity\Map\GisLayer;
use demosplan\DemosPlanCoreBundle\Entity\Map\GisLayerCategory;
use demosplan\DemosPlanCoreBundle\Entity\Procedure\Procedure;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,GisLayerCategory>
 *
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,GisLayerCategory,Procedure> $procedure {@link GisLayerCategory::procedure}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,GisLayerCategory> $name {@link GisLayerCategory::name}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,GisLayerCategory> $createDate {@link GisLayerCategory::createDate}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,GisLayerCategory> $modifyDate {@link GisLayerCategory::modifyDate}
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,GisLayerCategory,GisLayer> $gisLayers {@link GisLayerCategory::gisLayers}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,GisLayerCategory,GisLayerCategory> $parent {@link GisLayerCategory::parent}
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,GisLayerCategory,GisLayerCategory> $children {@link GisLayerCategory::children}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,GisLayerCategory> $treeOrder {@link GisLayerCategory::treeOrder}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,GisLayerCategory> $visible {@link GisLayerCategory::visible}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,GisLayerCategory> $layerWithChildrenHidden {@link GisLayerCategory::layerWithChildrenHidden}
 */
class BaseGisLayerCategoryResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
