<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\ResourceConfigBuilder;

use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;
use demosplan\DemosPlanCoreBundle\Entity\File;
use demosplan\DemosPlanCoreBundle\Entity\User\Customer;
use demosplan\DemosPlanCoreBundle\Entity\User\User;
use demosplan\DemosPlanCoreBundle\Entity\Video;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Video>
 *
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Video> $creationDate {@link Video::creationDate}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Video> $modificationDate {@link Video::modificationDate}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Video,User> $uploader {@link Video::uploader}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Video,Customer> $customerContext {@link Video::customerContext}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,Video,File> $file {@link Video::file}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Video> $title {@link Video::title}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,Video> $description {@link Video::description}
 */
class BaseVideoResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
