<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\ResourceConfigBuilder;

use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;
use demosplan\DemosPlanCoreBundle\Entity\OriginalStatementAnonymization;
use demosplan\DemosPlanCoreBundle\Entity\Statement\Statement;
use demosplan\DemosPlanCoreBundle\Entity\User\User;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,OriginalStatementAnonymization>
 *
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,OriginalStatementAnonymization> $created {@link OriginalStatementAnonymization::created}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,OriginalStatementAnonymization,Statement> $statement {@link OriginalStatementAnonymization::statement}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,OriginalStatementAnonymization,User> $createdBy {@link OriginalStatementAnonymization::createdBy}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,OriginalStatementAnonymization> $attachmentsDeleted {@link OriginalStatementAnonymization::attachmentsDeleted}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,OriginalStatementAnonymization> $textVersionHistoryDeleted {@link OriginalStatementAnonymization::textVersionHistoryDeleted}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,OriginalStatementAnonymization> $textPassagesAnonymized {@link OriginalStatementAnonymization::textPassagesAnonymized}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,OriginalStatementAnonymization> $submitterAndAuthorMetaDataAnonymized {@link OriginalStatementAnonymization::submitterAndAuthorMetaDataAnonymized}
 */
class BaseOriginalStatementAnonymizationResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
