<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\ResourceConfigBuilder;

use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToOneRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;
use demosplan\DemosPlanCoreBundle\Entity\Document\Elements;
use demosplan\DemosPlanCoreBundle\Entity\Document\ParagraphVersion;
use demosplan\DemosPlanCoreBundle\Entity\Document\SingleDocumentVersion;
use demosplan\DemosPlanCoreBundle\Entity\Procedure\Procedure;
use demosplan\DemosPlanCoreBundle\Entity\Statement\DraftStatement;
use demosplan\DemosPlanCoreBundle\Entity\Statement\DraftStatementVersion;
use demosplan\DemosPlanCoreBundle\Entity\User\Department;
use demosplan\DemosPlanCoreBundle\Entity\User\Orga;
use demosplan\DemosPlanCoreBundle\Entity\User\User;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,DraftStatementVersion>
 *
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,DraftStatementVersion,DraftStatement> $draftStatement {@link DraftStatementVersion::draftStatement}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,DraftStatementVersion,Procedure> $procedure {@link DraftStatementVersion::procedure}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DraftStatementVersion> $number {@link DraftStatementVersion::number}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DraftStatementVersion> $title {@link DraftStatementVersion::title}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DraftStatementVersion> $text {@link DraftStatementVersion::text}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,DraftStatementVersion,ParagraphVersion> $paragraph {@link DraftStatementVersion::paragraph}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,DraftStatementVersion,SingleDocumentVersion> $document {@link DraftStatementVersion::document}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,DraftStatementVersion,Elements> $element {@link DraftStatementVersion::element}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DraftStatementVersion> $polygon {@link DraftStatementVersion::polygon}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DraftStatementVersion> $file {@link DraftStatementVersion::file}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DraftStatementVersion> $mapFile {@link DraftStatementVersion::mapFile}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,DraftStatementVersion,Orga> $organisation {@link DraftStatementVersion::organisation}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DraftStatementVersion> $oName {@link DraftStatementVersion::oName}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DraftStatementVersion> $dName {@link DraftStatementVersion::dName}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,DraftStatementVersion,Department> $department {@link DraftStatementVersion::department}
 * @property-read ToOneRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,DraftStatementVersion,User> $user {@link DraftStatementVersion::user}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DraftStatementVersion> $uName {@link DraftStatementVersion::uName}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DraftStatementVersion> $uStreet {@link DraftStatementVersion::uStreet}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DraftStatementVersion> $uPostalCode {@link DraftStatementVersion::uPostalCode}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DraftStatementVersion> $uCity {@link DraftStatementVersion::uCity}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DraftStatementVersion> $uEmail {@link DraftStatementVersion::uEmail}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DraftStatementVersion> $feedback {@link DraftStatementVersion::feedback}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DraftStatementVersion> $externId {@link DraftStatementVersion::externId}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DraftStatementVersion> $rejectedReason {@link DraftStatementVersion::rejectedReason}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DraftStatementVersion> $negativ {@link DraftStatementVersion::negativ}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DraftStatementVersion> $submitted {@link DraftStatementVersion::submitted}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DraftStatementVersion> $released {@link DraftStatementVersion::released}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DraftStatementVersion> $showToAll {@link DraftStatementVersion::showToAll}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DraftStatementVersion> $deleted {@link DraftStatementVersion::deleted}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DraftStatementVersion> $rejected {@link DraftStatementVersion::rejected}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DraftStatementVersion> $publicAllowed {@link DraftStatementVersion::publicAllowed}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DraftStatementVersion> $publicUseName {@link DraftStatementVersion::publicUseName}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DraftStatementVersion> $publicDraftStatement {@link DraftStatementVersion::publicDraftStatement}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DraftStatementVersion> $phase {@link DraftStatementVersion::phase}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DraftStatementVersion> $versionDate {@link DraftStatementVersion::versionDate}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DraftStatementVersion> $createdDate {@link DraftStatementVersion::createdDate}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DraftStatementVersion> $deletedDate {@link DraftStatementVersion::deletedDate}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DraftStatementVersion> $lastModifiedDate {@link DraftStatementVersion::lastModifiedDate}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DraftStatementVersion> $submittedDate {@link DraftStatementVersion::submittedDate}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DraftStatementVersion> $releasedDate {@link DraftStatementVersion::releasedDate}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,DraftStatementVersion> $rejectedDate {@link DraftStatementVersion::rejectedDate}
 */
class BaseDraftStatementVersionResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
