<?php

declare(strict_types=1);

/**
 * This file is part of the package demosplan.
 *
 * (c) 2010-present DEMOS plan GmbH, for more information see the license file.
 *
 * All rights reserved
 */

namespace demosplan\DemosPlanCoreBundle\ResourceConfigBuilder;

use demosplan\DemosPlanCoreBundle\Entity\News\News;
use demosplan\DemosPlanCoreBundle\Entity\User\Role;
use EDT\DqlQuerying\Contracts\ClauseFunctionInterface;
use EDT\DqlQuerying\Contracts\OrderBySortMethodInterface;
use EDT\JsonApi\PropertyConfig\Builder\AttributeConfigBuilderInterface;
use EDT\JsonApi\PropertyConfig\Builder\ToManyRelationshipConfigBuilderInterface;
use EDT\JsonApi\ResourceConfig\Builder\MagicResourceConfigBuilder;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @template-extends MagicResourceConfigBuilder<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,News>
 *
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,News> $ident {@link News::ident}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,News> $pId {@link News::pId}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,News> $title {@link News::title}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,News> $description {@link News::description}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,News> $text {@link News::text}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,News> $picture {@link News::picture}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,News> $pictitle {@link News::pictitle}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,News> $pdf {@link News::pdf}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,News> $pdftitle {@link News::pdftitle}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,News> $enabled {@link News::enabled}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,News> $deleted {@link News::deleted}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,News> $createDate {@link News::createDate}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,News> $modifyDate {@link News::modifyDate}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,News> $deleteDate {@link News::deleteDate}
 * @property-read ToManyRelationshipConfigBuilderInterface<ClauseFunctionInterface<bool>,OrderBySortMethodInterface,News,Role> $roles {@link News::roles}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,News> $designatedSwitchDate {@link News::designatedSwitchDate}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,News> $designatedState {@link News::designatedState}
 * @property-read AttributeConfigBuilderInterface<ClauseFunctionInterface<bool>,News> $determinedToSwitch {@link News::determinedToSwitch}
 */
class BaseNewsResourceConfigBuilder extends MagicResourceConfigBuilder
{
}
