DemosPlanCore_annotations:
    resource: "../../demosplan/DemosPlanCoreBundle/Controller/"
    type: "attribute"
addon_routes:
    resource: 'demosplan\DemosPlanCoreBundle\Addon\AddonRoutingLoader::loadRoutes'
    type: service
