<?php

/**
 * This file is part of the package demosplan.
 *
 * (c) 2010-present DEMOS plan GmbH, for more information see the license file.
 *
 * All rights reserved
 */

namespace demosplan\DemosPlanCoreBundle\Command;


use Nette\PhpGenerator\PhpFile;
use ReflectionClass;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;
use Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface;
use Symfony\Component\Filesystem\Filesystem;


class GenerateEntityInterfaceCommand extends CoreCommand
{
    private const CORE_ENTITY_DIRECTORY = 'demosplan\\DemosPlanCoreBundle\\Entity';
    private const INTERFACE_NAMESPACE = 'DemosEurope\\DemosplanAddon\\Contracts\\Entities';
    protected static $defaultName = 'dplan:generate-entity-interface';
    public function __construct(ParameterBagInterface $parameterBag,
                                private readonly Filesystem $filesystem)
    {
        parent::__construct($parameterBag);

    }


    protected function configure(): void
    {
        $this
            ->setDescription('Generates interface for entity classes')
            ->setHelp('This command analyzes entity classes and generates corresponding interfaces')
            ->addArgument('entity', InputArgument::OPTIONAL, 'Entity name to generate interface for (optional)')
            ->addOption('output-dir', 'o', InputOption::VALUE_REQUIRED, 'Output directory for the generated interface', 'interface-repo/src/Contracts/Entities');
    }
    public function execute(InputInterface $input, OutputInterface $output): int
    {
        $output = new SymfonyStyle($input, $output);

        $entityName = $input->getArgument('entity');
        $outputDir = $input->getOption('output-dir');

        // Create output directory if it doesn't exist
        if (!$this->filesystem->exists($outputDir)) {
            $this->filesystem->mkdir($outputDir, 0755);
        }

        // Define paths
        $entityClass = self::CORE_ENTITY_DIRECTORY . '\\CustomFields\\' . $entityName;
        $interfacePath = $outputDir . '/' . $entityName . 'Interface.php';

        // Generate interface
        $interfaceContent = $this->generateInterfaceFromEntity($entityClass, $entityName);

        // Write interface file
        $this->filesystem->dumpFile($interfacePath, (string) $interfaceContent);


        $output->writeln("Generated interface for {$entityName}: {$interfacePath}");

        return Command::SUCCESS;
    }

    private function generateInterfaceFromEntity(string $entityClass, string $entityName): PhpFile
    {
        $newFile = new PhpFile();
        $newFile->setStrictTypes();
        $namespace = $newFile->addNamespace(self::INTERFACE_NAMESPACE);
        $interface = $namespace->addInterface($entityName . 'Interface');

        $interface->addComment('WARNING: THIS INTERFACE IS AUTOGENERATED.');
        $interface->addComment("MANUAL CHANGES WILL BE LOST ON RE-GENERATION.\n");




        // Use PHP reflection for analyzing the class
        $reflectionClass = new ReflectionClass($entityClass);



        foreach ($reflectionClass->getMethods(\ReflectionMethod::IS_PUBLIC) as $method) {
            $newMethod = $interface->addMethod($method->getName());
            $newMethod->setPublic();

            foreach ($method->getParameters() as $parameter) {
                $paramType = $parameter->getType();
                $newParam = $newMethod->addParameter($parameter->getName());

                if ($paramType !== null) {
                    $newParam->setType((string) $paramType);
                }

                if ($parameter->isDefaultValueAvailable()) {
                    $newParam->setDefaultValue($parameter->getDefaultValue());
                }
            }

            $returnType = $method->getReturnType();
            if ($returnType !== null) {
                $returnTypeName = (string) $returnType;
                if (!str_starts_with($returnTypeName, 'demosplan\\DemosPlanCoreBundle')) {
                    $newMethod->setReturnType($returnTypeName);
                }
            }
        }

        return $newFile;
    }

}
