<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;
use demosplan\DemosPlanCoreBundle\Entity\User\Address;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id {@link Address::id}
 * @property-read End $code {@link Address::code}
 * @property-read End $street {@link Address::street}
 * @property-read End $street1 {@link Address::street1}
 * @property-read End $postalcode {@link Address::postalcode}
 * @property-read End $city {@link Address::city}
 * @property-read End $region {@link Address::region}
 * @property-read End $state {@link Address::state}
 * @property-read End $postofficebox {@link Address::postofficebox}
 * @property-read End $phone {@link Address::phone}
 * @property-read End $fax {@link Address::fax}
 * @property-read End $email {@link Address::email}
 * @property-read End $url {@link Address::url}
 * @property-read End $createdDate {@link Address::createdDate}
 * @property-read End $modifiedDate {@link Address::modifiedDate}
 * @property-read End $deleted {@link Address::deleted}
 * @property-read End $houseNumber {@link Address::houseNumber}
 */
class AddressPath implements PropertyAutoPathInterface
{
	use PropertyAutoPathTrait;
}
