<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;
use demosplan\DemosPlanCoreBundle\Entity\User\AddressBookEntry;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id {@link AddressBookEntry::id}
 * @property-read End $name {@link AddressBookEntry::name}
 * @property-read OrgaPath $organisation {@link AddressBookEntry::organisation}
 * @property-read End $emailAddress {@link AddressBookEntry::emailAddress}
 * @property-read End $createdDate {@link AddressBookEntry::createdDate}
 * @property-read End $modifiedDate {@link AddressBookEntry::modifiedDate}
 */
class AddressBookEntryPath implements PropertyAutoPathInterface
{
	use PropertyAutoPathTrait;
}
