<?php

declare(strict_types=1);

/**
 * This file is part of the package demosplan.
 *
 * (c) 2010-present DEMOS plan GmbH, for more information see the license file.
 *
 * All rights reserved
 */

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use demosplan\DemosPlanCoreBundle\Entity\Procedure\BoilerplateCategory;
use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id {@link BoilerplateCategory::id}
 * @property-read ProcedurePath $procedure {@link BoilerplateCategory::procedure}
 * @property-read BoilerplatePath $boilerplates {@link BoilerplateCategory::boilerplates}
 * @property-read End $title {@link BoilerplateCategory::title}
 * @property-read End $description {@link BoilerplateCategory::description}
 * @property-read End $createDate {@link BoilerplateCategory::createDate}
 * @property-read End $modifyDate {@link BoilerplateCategory::modifyDate}
 */
class BoilerplateCategoryPath implements PropertyAutoPathInterface
{
    use PropertyAutoPathTrait;
}
