<?php

declare(strict_types=1);

/**
 * This file is part of the package demosplan.
 *
 * (c) 2010-present DEMOS plan GmbH, for more information see the license file.
 *
 * All rights reserved
 */

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use demosplan\DemosPlanCoreBundle\Entity\Procedure\Boilerplate;
use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $ident {@link Boilerplate::ident}
 * @property-read ProcedurePath $procedure {@link Boilerplate::procedure}
 * @property-read BoilerplateCategoryPath $categories {@link Boilerplate::categories}
 * @property-read BoilerplateGroupPath $group {@link Boilerplate::group}
 * @property-read TagPath $tags {@link Boilerplate::tags}
 * @property-read End $title {@link Boilerplate::title}
 * @property-read End $text {@link Boilerplate::text}
 * @property-read End $createDate {@link Boilerplate::createDate}
 * @property-read End $modifyDate {@link Boilerplate::modifyDate}
 */
class BoilerplatePath implements PropertyAutoPathInterface
{
    use PropertyAutoPathTrait;
}
