<?php

declare(strict_types=1);

/**
 * This file is part of the package demosplan.
 *
 * (c) 2010-present DEMOS plan GmbH, for more information see the license file.
 *
 * All rights reserved
 */

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use demosplan\DemosPlanCoreBundle\Entity\Category;
use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id {@link Category::id}
 * @property-read End $name {@link Category::name}
 * @property-read End $title {@link Category::title}
 * @property-read End $description {@link Category::description}
 * @property-read End $picture {@link Category::picture}
 * @property-read End $pictitle {@link Category::pictitle}
 * @property-read End $enabled {@link Category::enabled}
 * @property-read End $deleted {@link Category::deleted}
 * @property-read End $createDate {@link Category::createDate}
 * @property-read End $modifyDate {@link Category::modifyDate}
 * @property-read End $deleteDate {@link Category::deleteDate}
 * @property-read GlobalContentPath $globalContents {@link Category::globalContents}
 * @property-read End $custom {@link Category::custom}
 */
class CategoryPath implements PropertyAutoPathInterface
{
    use PropertyAutoPathTrait;
}
