<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;
use demosplan\DemosPlanCoreBundle\Entity\Statement\ConsultationToken;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id {@link ConsultationToken::id}
 * @property-read End $note {@link ConsultationToken::note}
 * @property-read StatementPath $originalStatement {@link ConsultationToken::originalStatement}
 * @property-read MailSendPath $sentEmail {@link ConsultationToken::sentEmail}
 * @property-read End $creationDate {@link ConsultationToken::creationDate}
 * @property-read End $modificationDate {@link ConsultationToken::modificationDate}
 * @property-read End $token {@link ConsultationToken::token}
 * @property-read StatementPath $statement {@link ConsultationToken::statement}
 * @property-read End $manuallyCreated {@link ConsultationToken::manuallyCreated}
 */
class ConsultationTokenPath implements PropertyAutoPathInterface
{
	use PropertyAutoPathTrait;
}
