<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;
use demosplan\DemosPlanCoreBundle\Entity\Statement\County;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id {@link County::id}
 * @property-read CustomerCountyPath $customerCounties {@link County::customerCounties}
 * @property-read End $name {@link County::name}
 * @property-read StatementPath $statements {@link County::statements}
 * @property-read StatementFragmentPath $statementFragments {@link County::statementFragments}
 */
class CountyPath implements PropertyAutoPathInterface
{
	use PropertyAutoPathTrait;
}
