<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;
use demosplan\DemosPlanCoreBundle\Entity\User\CustomerCounty;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id {@link CustomerCounty::id}
 * @property-read CustomerPath $customer {@link CustomerCounty::customer}
 * @property-read CountyPath $county {@link CustomerCounty::county}
 * @property-read End $eMailAddress {@link CustomerCounty::eMailAddress}
 */
class CustomerCountyPath implements PropertyAutoPathInterface
{
	use PropertyAutoPathTrait;
}
