<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;
use demosplan\DemosPlanCoreBundle\Entity\User\Customer;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id {@link Customer::id}
 * @property-read CustomerCountyPath $customerCounties {@link Customer::customerCounties}
 * @property-read End $imprint {@link Customer::imprint}
 * @property-read UserRoleInCustomerPath $userRoles {@link Customer::userRoles}
 * @property-read OrgaStatusInCustomerPath $orgaStatuses {@link Customer::orgaStatuses}
 * @property-read End $dataProtection {@link Customer::dataProtection}
 * @property-read End $termsOfUse {@link Customer::termsOfUse}
 * @property-read End $xplanning {@link Customer::xplanning}
 * @property-read ProcedurePath $defaultProcedureBlueprint {@link Customer::defaultProcedureBlueprint}
 * @property-read End $mapAttribution {@link Customer::mapAttribution}
 * @property-read End $baseLayerUrl {@link Customer::baseLayerUrl}
 * @property-read End $baseLayerLayers {@link Customer::baseLayerLayers}
 * @property-read BrandingPath $branding {@link Customer::branding}
 * @property-read End $accessibilityExplanation {@link Customer::accessibilityExplanation}
 * @property-read VideoPath $signLanguageOverviewVideos {@link Customer::signLanguageOverviewVideos}
 * @property-read End $signLanguageOverviewDescription {@link Customer::signLanguageOverviewDescription}
 * @property-read End $overviewDescriptionInSimpleLanguage {@link Customer::overviewDescriptionInSimpleLanguage}
 * @property-read SupportContactPath $contacts {@link Customer::contacts}
 * @property-read End $name {@link Customer::name}
 * @property-read End $subdomain {@link Customer::subdomain}
 */
class CustomerPath implements PropertyAutoPathInterface
{
	use PropertyAutoPathTrait;
}
