<?php

declare(strict_types=1);

/**
 * This file is part of the package demosplan.
 *
 * (c) 2010-present DEMOS plan GmbH, for more information see the license file.
 *
 * All rights reserved
 */

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use demosplan\DemosPlanCoreBundle\Entity\User\Department;
use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id {@link Department::id}
 * @property-read End $name {@link Department::name}
 * @property-read End $code {@link Department::code}
 * @property-read End $createdDate {@link Department::createdDate}
 * @property-read End $modifiedDate {@link Department::modifiedDate}
 * @property-read End $deleted {@link Department::deleted}
 * @property-read End $gwId {@link Department::gwId}
 * @property-read OrgaPath $orgas {@link Department::orgas}
 * @property-read AddressPath $addresses {@link Department::addresses}
 * @property-read UserPath $users {@link Department::users}
 */
class DepartmentPath implements PropertyAutoPathInterface
{
    use PropertyAutoPathTrait;
}
