<?php

declare(strict_types=1);

/**
 * This file is part of the package demosplan.
 *
 * (c) 2010-present DEMOS plan GmbH, for more information see the license file.
 *
 * All rights reserved
 */

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use demosplan\DemosPlanCoreBundle\Entity\Forum\DevelopmentUserStory;
use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $ident {@link DevelopmentUserStory::ident}
 * @property-read DevelopmentReleasePath $release {@link DevelopmentUserStory::release}
 * @property-read ForumThreadPath $thread {@link DevelopmentUserStory::thread}
 * @property-read End $onlineVotes {@link DevelopmentUserStory::onlineVotes}
 * @property-read End $offlineVotes {@link DevelopmentUserStory::offlineVotes}
 * @property-read End $description {@link DevelopmentUserStory::description}
 * @property-read End $title {@link DevelopmentUserStory::title}
 * @property-read End $modifiedDate {@link DevelopmentUserStory::modifiedDate}
 * @property-read End $createDate {@link DevelopmentUserStory::createDate}
 */
class DevelopmentUserStoryPath implements PropertyAutoPathInterface
{
    use PropertyAutoPathTrait;
}
