<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;
use demosplan\DemosPlanCoreBundle\Entity\Forum\DevelopmentRelease;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $ident {@link DevelopmentRelease::ident}
 * @property-read End $description {@link DevelopmentRelease::description}
 * @property-read End $title {@link DevelopmentRelease::title}
 * @property-read End $phase {@link DevelopmentRelease::phase}
 * @property-read End $startDate {@link DevelopmentRelease::startDate}
 * @property-read End $endDate {@link DevelopmentRelease::endDate}
 * @property-read End $modifiedDate {@link DevelopmentRelease::modifiedDate}
 * @property-read End $createDate {@link DevelopmentRelease::createDate}
 */
class DevelopmentReleasePath implements PropertyAutoPathInterface
{
	use PropertyAutoPathTrait;
}
