<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;
use demosplan\DemosPlanCoreBundle\Entity\Forum\DevelopmentUserStoryVote;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $ident {@link DevelopmentUserStoryVote::ident}
 * @property-read OrgaPath $orga {@link DevelopmentUserStoryVote::orga}
 * @property-read UserPath $user {@link DevelopmentUserStoryVote::user}
 * @property-read DevelopmentUserStoryPath $userStory {@link DevelopmentUserStoryVote::userStory}
 * @property-read End $numberOfVotes {@link DevelopmentUserStoryVote::numberOfVotes}
 * @property-read End $modifiedDate {@link DevelopmentUserStoryVote::modifiedDate}
 * @property-read End $createDate {@link DevelopmentUserStoryVote::createDate}
 */
class DevelopmentUserStoryVotePath implements PropertyAutoPathInterface
{
	use PropertyAutoPathTrait;
}
