<?php

declare(strict_types=1);

/**
 * This file is part of the package demosplan.
 *
 * (c) 2010-present DEMOS plan GmbH, for more information see the license file.
 *
 * All rights reserved
 */

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use demosplan\DemosPlanCoreBundle\Entity\Statement\DraftStatementVersion;
use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id {@link DraftStatementVersion::id}
 * @property-read DraftStatementPath $draftStatement {@link DraftStatementVersion::draftStatement}
 * @property-read ProcedurePath $procedure {@link DraftStatementVersion::procedure}
 * @property-read End $number {@link DraftStatementVersion::number}
 * @property-read End $title {@link DraftStatementVersion::title}
 * @property-read End $text {@link DraftStatementVersion::text}
 * @property-read ParagraphVersionPath $paragraph {@link DraftStatementVersion::paragraph}
 * @property-read SingleDocumentVersionPath $document {@link DraftStatementVersion::document}
 * @property-read ElementsPath $element {@link DraftStatementVersion::element}
 * @property-read End $polygon {@link DraftStatementVersion::polygon}
 * @property-read End $file {@link DraftStatementVersion::file}
 * @property-read End $mapFile {@link DraftStatementVersion::mapFile}
 * @property-read OrgaPath $organisation {@link DraftStatementVersion::organisation}
 * @property-read End $oName {@link DraftStatementVersion::oName}
 * @property-read End $dName {@link DraftStatementVersion::dName}
 * @property-read DepartmentPath $department {@link DraftStatementVersion::department}
 * @property-read UserPath $user {@link DraftStatementVersion::user}
 * @property-read End $uName {@link DraftStatementVersion::uName}
 * @property-read End $uStreet {@link DraftStatementVersion::uStreet}
 * @property-read End $uPostalCode {@link DraftStatementVersion::uPostalCode}
 * @property-read End $uCity {@link DraftStatementVersion::uCity}
 * @property-read End $uEmail {@link DraftStatementVersion::uEmail}
 * @property-read End $feedback {@link DraftStatementVersion::feedback}
 * @property-read End $externId {@link DraftStatementVersion::externId}
 * @property-read End $rejectedReason {@link DraftStatementVersion::rejectedReason}
 * @property-read End $negativ {@link DraftStatementVersion::negativ}
 * @property-read End $submitted {@link DraftStatementVersion::submitted}
 * @property-read End $released {@link DraftStatementVersion::released}
 * @property-read End $showToAll {@link DraftStatementVersion::showToAll}
 * @property-read End $deleted {@link DraftStatementVersion::deleted}
 * @property-read End $rejected {@link DraftStatementVersion::rejected}
 * @property-read End $publicAllowed {@link DraftStatementVersion::publicAllowed}
 * @property-read End $publicUseName {@link DraftStatementVersion::publicUseName}
 * @property-read End $publicDraftStatement {@link DraftStatementVersion::publicDraftStatement}
 * @property-read End $phase {@link DraftStatementVersion::phase}
 * @property-read End $versionDate {@link DraftStatementVersion::versionDate}
 * @property-read End $createdDate {@link DraftStatementVersion::createdDate}
 * @property-read End $deletedDate {@link DraftStatementVersion::deletedDate}
 * @property-read End $lastModifiedDate {@link DraftStatementVersion::lastModifiedDate}
 * @property-read End $submittedDate {@link DraftStatementVersion::submittedDate}
 * @property-read End $releasedDate {@link DraftStatementVersion::releasedDate}
 * @property-read End $rejectedDate {@link DraftStatementVersion::rejectedDate}
 */
class DraftStatementVersionPath implements PropertyAutoPathInterface
{
    use PropertyAutoPathTrait;
}
