<?php

declare(strict_types=1);

/**
 * This file is part of the package demosplan.
 *
 * (c) 2010-present DEMOS plan GmbH, for more information see the license file.
 *
 * All rights reserved
 */

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use demosplan\DemosPlanCoreBundle\Entity\EntityContentChange;
use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id {@link EntityContentChange::id}
 * @property-read End $created {@link EntityContentChange::created}
 * @property-read End $modified {@link EntityContentChange::modified}
 * @property-read End $userId {@link EntityContentChange::userId}
 * @property-read End $userName {@link EntityContentChange::userName}
 * @property-read End $entityType {@link EntityContentChange::entityType}
 * @property-read End $entityId {@link EntityContentChange::entityId}
 * @property-read End $entityField {@link EntityContentChange::entityField}
 * @property-read End $preUpdate {@link EntityContentChange::preUpdate}
 * @property-read End $postUpdate {@link EntityContentChange::postUpdate}
 * @property-read End $contentChange {@link EntityContentChange::contentChange}
 */
class EntityContentChangePath implements PropertyAutoPathInterface
{
    use PropertyAutoPathTrait;
}
