<?php

declare(strict_types=1);

/**
 * This file is part of the package demosplan.
 *
 * (c) 2010-present DEMOS plan GmbH, for more information see the license file.
 *
 * All rights reserved
 */

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use demosplan\DemosPlanCoreBundle\Entity\ExportFieldsConfiguration;
use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id {@link ExportFieldsConfiguration::id}
 * @property-read ProcedurePath $procedure {@link ExportFieldsConfiguration::procedure}
 * @property-read End $creationDate {@link ExportFieldsConfiguration::creationDate}
 * @property-read End $modificationDate {@link ExportFieldsConfiguration::modificationDate}
 * @property-read End $idExportable {@link ExportFieldsConfiguration::idExportable}
 * @property-read End $statementNameExportable {@link ExportFieldsConfiguration::statementNameExportable}
 * @property-read End $creationDateExportable {@link ExportFieldsConfiguration::creationDateExportable}
 * @property-read End $procedureNameExportable {@link ExportFieldsConfiguration::procedureNameExportable}
 * @property-read End $procedurePhaseExportable {@link ExportFieldsConfiguration::procedurePhaseExportable}
 * @property-read End $votesNumExportable {@link ExportFieldsConfiguration::votesNumExportable}
 * @property-read End $userStateExportable {@link ExportFieldsConfiguration::userStateExportable}
 * @property-read End $userGroupExportable {@link ExportFieldsConfiguration::userGroupExportable}
 * @property-read End $userOrganisationExportable {@link ExportFieldsConfiguration::userOrganisationExportable}
 * @property-read End $userPositionExportable {@link ExportFieldsConfiguration::userPositionExportable}
 * @property-read End $institutionExportable {@link ExportFieldsConfiguration::institutionExportable}
 * @property-read End $publicParticipationExportable {@link ExportFieldsConfiguration::publicParticipationExportable}
 * @property-read End $orgaNameExportable {@link ExportFieldsConfiguration::orgaNameExportable}
 * @property-read End $departmentNameExportable {@link ExportFieldsConfiguration::departmentNameExportable}
 * @property-read End $submitterNameExportable {@link ExportFieldsConfiguration::submitterNameExportable}
 * @property-read End $showInPublicAreaExportable {@link ExportFieldsConfiguration::showInPublicAreaExportable}
 * @property-read End $documentExportable {@link ExportFieldsConfiguration::documentExportable}
 * @property-read End $paragraphExportable {@link ExportFieldsConfiguration::paragraphExportable}
 * @property-read End $filesExportable {@link ExportFieldsConfiguration::filesExportable}
 * @property-read End $attachmentsExportable {@link ExportFieldsConfiguration::attachmentsExportable}
 * @property-read End $priorityExportable {@link ExportFieldsConfiguration::priorityExportable}
 * @property-read End $emailExportable {@link ExportFieldsConfiguration::emailExportable}
 * @property-read End $phoneNumberExportable {@link ExportFieldsConfiguration::phoneNumberExportable}
 * @property-read End $streetExportable {@link ExportFieldsConfiguration::streetExportable}
 * @property-read End $streetNumberExportable {@link ExportFieldsConfiguration::streetNumberExportable}
 * @property-read End $postalCodeExportable {@link ExportFieldsConfiguration::postalCodeExportable}
 * @property-read End $cityExportable {@link ExportFieldsConfiguration::cityExportable}
 * @property-read End $institutionOrCitizenExportable {@link ExportFieldsConfiguration::institutionOrCitizenExportable}
 */
class ExportFieldsConfigurationPath implements PropertyAutoPathInterface
{
    use PropertyAutoPathTrait;
}
