<?php

declare(strict_types=1);

/**
 * This file is part of the package demosplan.
 *
 * (c) 2010-present DEMOS plan GmbH, for more information see the license file.
 *
 * All rights reserved
 */

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use demosplan\DemosPlanCoreBundle\Entity\FaqCategory;
use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id {@link FaqCategory::id}
 * @property-read End $title {@link FaqCategory::title}
 * @property-read End $type {@link FaqCategory::type}
 * @property-read End $createDate {@link FaqCategory::createDate}
 * @property-read End $modifyDate {@link FaqCategory::modifyDate}
 * @property-read CustomerPath $customer {@link FaqCategory::customer}
 */
class FaqCategoryPath implements PropertyAutoPathInterface
{
    use PropertyAutoPathTrait;
}
