<?php

declare(strict_types=1);

/**
 * This file is part of the package demosplan.
 *
 * (c) 2010-present DEMOS plan GmbH, for more information see the license file.
 *
 * All rights reserved
 */

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use demosplan\DemosPlanCoreBundle\Entity\File;
use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id {@link File::id}
 * @property-read End $ident {@link File::ident}
 * @property-read End $hash {@link File::hash}
 * @property-read End $name {@link File::name}
 * @property-read End $description {@link File::description}
 * @property-read End $path {@link File::path}
 * @property-read End $filename {@link File::filename}
 * @property-read End $tags {@link File::tags}
 * @property-read End $author {@link File::author}
 * @property-read End $application {@link File::application}
 * @property-read End $mimetype {@link File::mimetype}
 * @property-read End $created {@link File::created}
 * @property-read End $modified {@link File::modified}
 * @property-read End $validUntil {@link File::validUntil}
 * @property-read End $deleted {@link File::deleted}
 * @property-read End $statDown {@link File::statDown}
 * @property-read End $infected {@link File::infected}
 * @property-read End $lastVScan {@link File::lastVScan}
 * @property-read End $blocked {@link File::blocked}
 * @property-read End $size {@link File::size}
 * @property-read ProcedurePath $procedure {@link File::procedure}
 */
class FilePath implements PropertyAutoPathInterface
{
    use PropertyAutoPathTrait;
}
