<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;
use demosplan\DemosPlanCoreBundle\Entity\Flood;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id {@link Flood::id}
 * @property-read End $event {@link Flood::event}
 * @property-read End $identifier {@link Flood::identifier}
 * @property-read End $created {@link Flood::created}
 * @property-read End $expires {@link Flood::expires}
 */
class FloodPath implements PropertyAutoPathInterface
{
	use PropertyAutoPathTrait;
}
