<?php

declare(strict_types=1);

/**
 * This file is part of the package demosplan.
 *
 * (c) 2010-present DEMOS plan GmbH, for more information see the license file.
 *
 * All rights reserved
 */

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use demosplan\DemosPlanCoreBundle\Entity\Forum\ForumThread;
use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $ident {@link ForumThread::ident}
 * @property-read End $url {@link ForumThread::url}
 * @property-read End $closed {@link ForumThread::closed}
 * @property-read End $closingReason {@link ForumThread::closingReason}
 * @property-read End $progression {@link ForumThread::progression}
 * @property-read End $createDate {@link ForumThread::createDate}
 * @property-read End $modifyDate {@link ForumThread::modifyDate}
 */
class ForumThreadPath implements PropertyAutoPathInterface
{
    use PropertyAutoPathTrait;
}
