<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;
use demosplan\DemosPlanCoreBundle\Entity\Forum\ForumEntryFile;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $ident {@link ForumEntryFile::ident}
 * @property-read End $entryId {@link ForumEntryFile::entryId}
 * @property-read ForumEntryPath $entry {@link ForumEntryFile::entry}
 * @property-read End $createDate {@link ForumEntryFile::createDate}
 * @property-read End $modifyDate {@link ForumEntryFile::modifyDate}
 * @property-read End $deleted {@link ForumEntryFile::deleted}
 * @property-read End $blocked {@link ForumEntryFile::blocked}
 * @property-read End $order {@link ForumEntryFile::order}
 * @property-read End $string {@link ForumEntryFile::string}
 * @property-read End $hash {@link ForumEntryFile::hash}
 */
class ForumEntryFilePath implements PropertyAutoPathInterface
{
	use PropertyAutoPathTrait;
}
