<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;
use demosplan\DemosPlanCoreBundle\Entity\Forum\ForumEntry;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $ident {@link ForumEntry::ident}
 * @property-read ForumThreadPath $thread {@link ForumEntry::thread}
 * @property-read UserPath $user {@link ForumEntry::user}
 * @property-read End $userRoles {@link ForumEntry::userRoles}
 * @property-read End $text {@link ForumEntry::text}
 * @property-read End $initialEntry {@link ForumEntry::initialEntry}
 * @property-read End $createDate {@link ForumEntry::createDate}
 * @property-read End $modifyDate {@link ForumEntry::modifyDate}
 */
class ForumEntryPath implements PropertyAutoPathInterface
{
	use PropertyAutoPathTrait;
}
