<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;
use demosplan\DemosPlanCoreBundle\Entity\Statement\GdprConsentRevokeToken;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id {@link GdprConsentRevokeToken::id}
 * @property-read StatementPath $statements {@link GdprConsentRevokeToken::statements}
 * @property-read End $token {@link GdprConsentRevokeToken::token}
 * @property-read EmailAddressPath $emailAddress {@link GdprConsentRevokeToken::emailAddress}
 */
class GdprConsentRevokeTokenPath implements PropertyAutoPathInterface
{
	use PropertyAutoPathTrait;
}
