<?php

declare(strict_types=1);

/**
 * This file is part of the package demosplan.
 *
 * (c) 2010-present DEMOS plan GmbH, for more information see the license file.
 *
 * All rights reserved
 */

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use demosplan\DemosPlanCoreBundle\Entity\Map\GisLayerCategory;
use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id {@link GisLayerCategory::id}
 * @property-read ProcedurePath $procedure {@link GisLayerCategory::procedure}
 * @property-read End $name {@link GisLayerCategory::name}
 * @property-read End $createDate {@link GisLayerCategory::createDate}
 * @property-read End $modifyDate {@link GisLayerCategory::modifyDate}
 * @property-read GisLayerPath $gisLayers {@link GisLayerCategory::gisLayers}
 * @property-read GisLayerCategoryPath $parent {@link GisLayerCategory::parent}
 * @property-read GisLayerCategoryPath $children {@link GisLayerCategory::children}
 * @property-read End $treeOrder {@link GisLayerCategory::treeOrder}
 * @property-read End $visible {@link GisLayerCategory::visible}
 * @property-read End $layerWithChildrenHidden {@link GisLayerCategory::layerWithChildrenHidden}
 */
class GisLayerCategoryPath implements PropertyAutoPathInterface
{
    use PropertyAutoPathTrait;
}
