<?php

declare(strict_types=1);

/**
 * This file is part of the package demosplan.
 *
 * (c) 2010-present DEMOS plan GmbH, for more information see the license file.
 *
 * All rights reserved
 */

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use demosplan\DemosPlanCoreBundle\Entity\Map\GisLayer;
use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $ident {@link GisLayer::ident}
 * @property-read End $bplan {@link GisLayer::bplan}
 * @property-read End $defaultVisibility {@link GisLayer::defaultVisibility}
 * @property-read End $deleted {@link GisLayer::deleted}
 * @property-read End $legend {@link GisLayer::legend}
 * @property-read End $layers {@link GisLayer::layers}
 * @property-read End $name {@link GisLayer::name}
 * @property-read End $opacity {@link GisLayer::opacity}
 * @property-read End $order {@link GisLayer::order}
 * @property-read End $projectionLabel {@link GisLayer::projectionLabel}
 * @property-read End $projectionValue {@link GisLayer::projectionValue}
 * @property-read End $procedureId {@link GisLayer::procedureId}
 * @property-read End $print {@link GisLayer::print}
 * @property-read End $scope {@link GisLayer::scope}
 * @property-read End $scope1 {@link GisLayer::scope1}
 * @property-read End $type {@link GisLayer::type}
 * @property-read End $serviceType {@link GisLayer::serviceType}
 * @property-read End $capabilities {@link GisLayer::capabilities}
 * @property-read End $tileMatrixSet {@link GisLayer::tileMatrixSet}
 * @property-read End $url {@link GisLayer::url}
 * @property-read End $enabled {@link GisLayer::enabled}
 * @property-read End $gId {@link GisLayer::gId}
 * @property-read End $layerVersion {@link GisLayer::layerVersion}
 * @property-read End $xplan {@link GisLayer::xplan}
 * @property-read End $createDate {@link GisLayer::createDate}
 * @property-read End $modifyDate {@link GisLayer::modifyDate}
 * @property-read End $deleteDate {@link GisLayer::deleteDate}
 * @property-read ContextualHelpPath $contextualHelp {@link GisLayer::contextualHelp}
 * @property-read GisLayerCategoryPath $category {@link GisLayer::category}
 * @property-read End $treeOrder {@link GisLayer::treeOrder}
 * @property-read End $userToggleVisibility {@link GisLayer::userToggleVisibility}
 * @property-read End $visibilityGroupId {@link GisLayer::visibilityGroupId}
 * @property-read End $isMiniMap {@link GisLayer::isMiniMap}
 */
class GisLayerPath implements PropertyAutoPathInterface
{
    use PropertyAutoPathTrait;
}
