<?php

declare(strict_types=1);

/**
 * This file is part of the package demosplan.
 *
 * (c) 2010-present DEMOS plan GmbH, for more information see the license file.
 *
 * All rights reserved
 */

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use demosplan\DemosPlanCoreBundle\Entity\GlobalContent;
use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $ident {@link GlobalContent::ident}
 * @property-read End $type {@link GlobalContent::type}
 * @property-read End $title {@link GlobalContent::title}
 * @property-read End $description {@link GlobalContent::description}
 * @property-read End $text {@link GlobalContent::text}
 * @property-read End $picture {@link GlobalContent::picture}
 * @property-read End $pictitle {@link GlobalContent::pictitle}
 * @property-read End $pdf {@link GlobalContent::pdf}
 * @property-read End $pdftitle {@link GlobalContent::pdftitle}
 * @property-read End $enabled {@link GlobalContent::enabled}
 * @property-read End $deleted {@link GlobalContent::deleted}
 * @property-read End $createDate {@link GlobalContent::createDate}
 * @property-read End $modifyDate {@link GlobalContent::modifyDate}
 * @property-read End $deleteDate {@link GlobalContent::deleteDate}
 * @property-read RolePath $roles {@link GlobalContent::roles}
 * @property-read CategoryPath $categories {@link GlobalContent::categories}
 */
class GlobalContentPath implements PropertyAutoPathInterface
{
    use PropertyAutoPathTrait;
}
