<?php

declare(strict_types=1);

/**
 * This file is part of the package demosplan.
 *
 * (c) 2010-present DEMOS plan GmbH, for more information see the license file.
 *
 * All rights reserved
 */

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use demosplan\DemosPlanCoreBundle\Entity\Procedure\HashedQuery;
use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id {@link HashedQuery::id}
 * @property-read End $hash {@link HashedQuery::hash}
 * @property-read End $storedQuery {@link HashedQuery::storedQuery}
 * @property-read End $created {@link HashedQuery::created}
 * @property-read End $modified {@link HashedQuery::modified}
 * @property-read ProcedurePath $procedure {@link HashedQuery::procedure}
 */
class HashedQueryPath implements PropertyAutoPathInterface
{
    use PropertyAutoPathTrait;
}
