<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;
use demosplan\DemosPlanCoreBundle\Entity\User\InstitutionTag;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id {@link InstitutionTag::id}
 * @property-read End $label {@link InstitutionTag::label}
 * @property-read OrgaPath $taggedInstitutions {@link InstitutionTag::taggedInstitutions}
 * @property-read OrgaPath $owningOrganisation {@link InstitutionTag::owningOrganisation}
 * @property-read End $creationDate {@link InstitutionTag::creationDate}
 * @property-read End $modificationDate {@link InstitutionTag::modificationDate}
 */
class InstitutionTagPath implements PropertyAutoPathInterface
{
	use PropertyAutoPathTrait;
}
