<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;
use demosplan\DemosPlanCoreBundle\Entity\Procedure\InstitutionMail;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id {@link InstitutionMail::id}
 * @property-read ProcedurePath $procedure {@link InstitutionMail::procedure}
 * @property-read OrgaPath $organisation {@link InstitutionMail::organisation}
 * @property-read End $procedurePhase {@link InstitutionMail::procedurePhase}
 * @property-read End $createdDate {@link InstitutionMail::createdDate}
 */
class InstitutionMailPath implements PropertyAutoPathInterface
{
	use PropertyAutoPathTrait;
}
