<?php

declare(strict_types=1);

/**
 * This file is part of the package demosplan.
 *
 * (c) 2010-present DEMOS plan GmbH, for more information see the license file.
 *
 * All rights reserved
 */

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use demosplan\DemosPlanCoreBundle\Entity\Location;
use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id {@link Location::id}
 * @property-read End $postcode {@link Location::postcode}
 * @property-read End $name {@link Location::name}
 * @property-read End $municipalCode {@link Location::municipalCode}
 * @property-read End $ars {@link Location::ars}
 * @property-read End $lat {@link Location::lat}
 * @property-read End $lon {@link Location::lon}
 */
class LocationPath implements PropertyAutoPathInterface
{
    use PropertyAutoPathTrait;
}
