<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;
use demosplan\DemosPlanCoreBundle\Entity\MailAttachment;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id {@link MailAttachment::id}
 * @property-read MailSendPath $mailSend {@link MailAttachment::mailSend}
 * @property-read End $filename {@link MailAttachment::filename}
 * @property-read End $deleteOnSent {@link MailAttachment::deleteOnSent}
 */
class MailAttachmentPath implements PropertyAutoPathInterface
{
	use PropertyAutoPathTrait;
}
