<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;
use demosplan\DemosPlanCoreBundle\Entity\ManualListSort;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id {@link ManualListSort::id}
 * @property-read End $pId {@link ManualListSort::pId}
 * @property-read End $context {@link ManualListSort::context}
 * @property-read End $namespace {@link ManualListSort::namespace}
 * @property-read End $idents {@link ManualListSort::idents}
 */
class ManualListSortPath implements PropertyAutoPathInterface
{
	use PropertyAutoPathTrait;
}
