<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;
use demosplan\DemosPlanCoreBundle\Entity\User\MasterToebVersion;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $ident {@link MasterToebVersion::ident}
 * @property-read MasterToebPath $masterToeb {@link MasterToebVersion::masterToeb}
 * @property-read End $gatewayGroup {@link MasterToebVersion::gatewayGroup}
 * @property-read End $orgaName {@link MasterToebVersion::orgaName}
 * @property-read OrgaPath $orga {@link MasterToebVersion::orga}
 * @property-read DepartmentPath $department {@link MasterToebVersion::department}
 * @property-read End $departmentName {@link MasterToebVersion::departmentName}
 * @property-read End $sign {@link MasterToebVersion::sign}
 * @property-read End $email {@link MasterToebVersion::email}
 * @property-read End $ccEmail {@link MasterToebVersion::ccEmail}
 * @property-read End $contactPerson {@link MasterToebVersion::contactPerson}
 * @property-read End $memo {@link MasterToebVersion::memo}
 * @property-read End $comment {@link MasterToebVersion::comment}
 * @property-read End $registered {@link MasterToebVersion::registered}
 * @property-read End $districtHHMitte {@link MasterToebVersion::districtHHMitte}
 * @property-read End $districtEimsbuettel {@link MasterToebVersion::districtEimsbuettel}
 * @property-read End $districtAltona {@link MasterToebVersion::districtAltona}
 * @property-read End $districtHHNord {@link MasterToebVersion::districtHHNord}
 * @property-read End $districtWandsbek {@link MasterToebVersion::districtWandsbek}
 * @property-read End $districtBergedorf {@link MasterToebVersion::districtBergedorf}
 * @property-read End $districtHarburg {@link MasterToebVersion::districtHarburg}
 * @property-read End $districtBsu {@link MasterToebVersion::districtBsu}
 * @property-read End $documentRoughAgreement {@link MasterToebVersion::documentRoughAgreement}
 * @property-read End $documentAgreement {@link MasterToebVersion::documentAgreement}
 * @property-read End $documentNotice {@link MasterToebVersion::documentNotice}
 * @property-read End $documentAssessment {@link MasterToebVersion::documentAssessment}
 * @property-read End $createdDate {@link MasterToebVersion::createdDate}
 * @property-read End $modifiedDate {@link MasterToebVersion::modifiedDate}
 * @property-read End $versionDate {@link MasterToebVersion::versionDate}
 */
class MasterToebVersionPath implements PropertyAutoPathInterface
{
	use PropertyAutoPathTrait;
}
