<?php

declare(strict_types=1);

/**
 * This file is part of the package demosplan.
 *
 * (c) 2010-present DEMOS plan GmbH, for more information see the license file.
 *
 * All rights reserved
 */

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use demosplan\DemosPlanCoreBundle\Entity\User\MasterToeb;
use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $ident {@link MasterToeb::ident}
 * @property-read End $gatewayGroup {@link MasterToeb::gatewayGroup}
 * @property-read End $orgaName {@link MasterToeb::orgaName}
 * @property-read OrgaPath $orga {@link MasterToeb::orga}
 * @property-read End $oId {@link MasterToeb::oId}
 * @property-read DepartmentPath $department {@link MasterToeb::department}
 * @property-read End $departmentName {@link MasterToeb::departmentName}
 * @property-read End $sign {@link MasterToeb::sign}
 * @property-read End $email {@link MasterToeb::email}
 * @property-read End $ccEmail {@link MasterToeb::ccEmail}
 * @property-read End $contactPerson {@link MasterToeb::contactPerson}
 * @property-read End $memo {@link MasterToeb::memo}
 * @property-read End $comment {@link MasterToeb::comment}
 * @property-read End $registered {@link MasterToeb::registered}
 * @property-read End $districtHHMitte {@link MasterToeb::districtHHMitte}
 * @property-read End $districtEimsbuettel {@link MasterToeb::districtEimsbuettel}
 * @property-read End $districtAltona {@link MasterToeb::districtAltona}
 * @property-read End $districtHHNord {@link MasterToeb::districtHHNord}
 * @property-read End $districtWandsbek {@link MasterToeb::districtWandsbek}
 * @property-read End $districtBergedorf {@link MasterToeb::districtBergedorf}
 * @property-read End $districtHarburg {@link MasterToeb::districtHarburg}
 * @property-read End $districtBsu {@link MasterToeb::districtBsu}
 * @property-read End $documentRoughAgreement {@link MasterToeb::documentRoughAgreement}
 * @property-read End $documentAgreement {@link MasterToeb::documentAgreement}
 * @property-read End $documentNotice {@link MasterToeb::documentNotice}
 * @property-read End $documentAssessment {@link MasterToeb::documentAssessment}
 * @property-read End $createdDate {@link MasterToeb::createdDate}
 * @property-read End $modifiedDate {@link MasterToeb::modifiedDate}
 */
class MasterToebPath implements PropertyAutoPathInterface
{
    use PropertyAutoPathTrait;
}
