<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;
use demosplan\DemosPlanCoreBundle\Entity\MigrationVersions;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $version {@link MigrationVersions::version}
 */
class MigrationVersionsPath implements PropertyAutoPathInterface
{
	use PropertyAutoPathTrait;
}
