<?php

declare(strict_types=1);

/**
 * This file is part of the package demosplan.
 *
 * (c) 2010-present DEMOS plan GmbH, for more information see the license file.
 *
 * All rights reserved
 */

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use demosplan\DemosPlanCoreBundle\Entity\Statement\Municipality;
use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id {@link Municipality::id}
 * @property-read End $name {@link Municipality::name}
 * @property-read End $officialMunicipalityKey {@link Municipality::officialMunicipalityKey}
 * @property-read StatementPath $statements {@link Municipality::statements}
 * @property-read StatementFragmentPath $statementFragments {@link Municipality::statementFragments}
 */
class MunicipalityPath implements PropertyAutoPathInterface
{
    use PropertyAutoPathTrait;
}
