<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;
use demosplan\DemosPlanCoreBundle\Entity\Statement\Municipality;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id {@link Municipality::id}
 * @property-read End $name {@link Municipality::name}
 * @property-read End $officialMunicipalityKey {@link Municipality::officialMunicipalityKey}
 * @property-read StatementPath $statements {@link Municipality::statements}
 * @property-read StatementFragmentPath $statementFragments {@link Municipality::statementFragments}
 */
class MunicipalityPath implements PropertyAutoPathInterface
{
	use PropertyAutoPathTrait;
}
