<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;
use demosplan\DemosPlanCoreBundle\Entity\OpenGeoDbShortTable;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $uniqueId {@link OpenGeoDbShortTable::uniqueId}
 * @property-read End $id {@link OpenGeoDbShortTable::id}
 * @property-read End $postcode {@link OpenGeoDbShortTable::postcode}
 * @property-read End $city {@link OpenGeoDbShortTable::city}
 * @property-read End $municipalCode {@link OpenGeoDbShortTable::municipalCode}
 * @property-read End $state {@link OpenGeoDbShortTable::state}
 * @property-read End $lat {@link OpenGeoDbShortTable::lat}
 * @property-read End $lon {@link OpenGeoDbShortTable::lon}
 */
class OpenGeoDbShortTablePath implements PropertyAutoPathInterface
{
	use PropertyAutoPathTrait;
}
