<?php

declare(strict_types=1);

/**
 * This file is part of the package demosplan.
 *
 * (c) 2010-present DEMOS plan GmbH, for more information see the license file.
 *
 * All rights reserved
 */

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use demosplan\DemosPlanCoreBundle\Entity\User\OrgaStatusInCustomer;
use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id {@link OrgaStatusInCustomer::id}
 * @property-read OrgaPath $orga {@link OrgaStatusInCustomer::orga}
 * @property-read OrgaTypePath $orgaType {@link OrgaStatusInCustomer::orgaType}
 * @property-read CustomerPath $customer {@link OrgaStatusInCustomer::customer}
 * @property-read End $status {@link OrgaStatusInCustomer::status}
 */
class OrgaStatusInCustomerPath implements PropertyAutoPathInterface
{
    use PropertyAutoPathTrait;
}
