<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;
use demosplan\DemosPlanCoreBundle\Entity\User\OrgaType;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id {@link OrgaType::id}
 * @property-read End $name {@link OrgaType::name}
 * @property-read End $label {@link OrgaType::label}
 * @property-read OrgaStatusInCustomerPath $orgaStatusInCustomers {@link OrgaType::orgaStatusInCustomers}
 */
class OrgaTypePath implements PropertyAutoPathInterface
{
	use PropertyAutoPathTrait;
}
