<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;
use demosplan\DemosPlanCoreBundle\Entity\OriginalStatementAnonymization;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id {@link OriginalStatementAnonymization::id}
 * @property-read End $created {@link OriginalStatementAnonymization::created}
 * @property-read StatementPath $statement {@link OriginalStatementAnonymization::statement}
 * @property-read UserPath $createdBy {@link OriginalStatementAnonymization::createdBy}
 * @property-read End $attachmentsDeleted {@link OriginalStatementAnonymization::attachmentsDeleted}
 * @property-read End $textVersionHistoryDeleted {@link OriginalStatementAnonymization::textVersionHistoryDeleted}
 * @property-read End $textPassagesAnonymized {@link OriginalStatementAnonymization::textPassagesAnonymized}
 * @property-read End $submitterAndAuthorMetaDataAnonymized {@link OriginalStatementAnonymization::submitterAndAuthorMetaDataAnonymized}
 */
class OriginalStatementAnonymizationPath implements PropertyAutoPathInterface
{
	use PropertyAutoPathTrait;
}
