<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;
use demosplan\DemosPlanCoreBundle\Entity\Document\ParagraphVersion;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id {@link ParagraphVersion::id}
 * @property-read ParagraphPath $paragraph {@link ParagraphVersion::paragraph}
 * @property-read ProcedurePath $procedure {@link ParagraphVersion::procedure}
 * @property-read ElementsPath $element {@link ParagraphVersion::element}
 * @property-read End $category {@link ParagraphVersion::category}
 * @property-read End $title {@link ParagraphVersion::title}
 * @property-read End $text {@link ParagraphVersion::text}
 * @property-read End $order {@link ParagraphVersion::order}
 * @property-read End $visible {@link ParagraphVersion::visible}
 * @property-read End $deleted {@link ParagraphVersion::deleted}
 * @property-read End $versionDate {@link ParagraphVersion::versionDate}
 * @property-read End $createDate {@link ParagraphVersion::createDate}
 * @property-read End $modifyDate {@link ParagraphVersion::modifyDate}
 * @property-read End $deleteDate {@link ParagraphVersion::deleteDate}
 */
class ParagraphVersionPath implements PropertyAutoPathInterface
{
	use PropertyAutoPathTrait;
}
