<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;
use demosplan\DemosPlanCoreBundle\Entity\Document\Paragraph;
use demosplan\DemosPlanCoreBundle\EntityPath\ParagraphPath as ParagraphPath1;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id {@link Paragraph::id}
 * @property-read ProcedurePath $procedure {@link Paragraph::procedure}
 * @property-read ParagraphPath $parent {@link Paragraph::parent}
 * @property-read ParagraphPath $children {@link Paragraph::children}
 * @property-read ElementsPath $element {@link Paragraph::element}
 * @property-read End $category {@link Paragraph::category}
 * @property-read End $title {@link Paragraph::title}
 * @property-read End $text {@link Paragraph::text}
 * @property-read End $order {@link Paragraph::order}
 * @property-read End $visible {@link Paragraph::visible}
 * @property-read End $deleted {@link Paragraph::deleted}
 * @property-read End $lockReason {@link Paragraph::lockReason}
 * @property-read End $createDate {@link Paragraph::createDate}
 * @property-read End $modifyDate {@link Paragraph::modifyDate}
 * @property-read End $deleteDate {@link Paragraph::deleteDate}
 * @property-read ParagraphVersionPath $versions {@link Paragraph::versions}
 */
class ParagraphPath implements PropertyAutoPathInterface
{
	use PropertyAutoPathTrait;
}
