<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;
use demosplan\DemosPlanCoreBundle\Entity\PlatformFaqCategory;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id {@link PlatformFaqCategory::id}
 * @property-read End $title {@link PlatformFaqCategory::title}
 * @property-read End $createDate {@link PlatformFaqCategory::createDate}
 * @property-read End $modifyDate {@link PlatformFaqCategory::modifyDate}
 */
class PlatformFaqCategoryPath implements PropertyAutoPathInterface
{
	use PropertyAutoPathTrait;
}
