<?php

declare(strict_types=1);

/**
 * This file is part of the package demosplan.
 *
 * (c) 2010-present DEMOS plan GmbH, for more information see the license file.
 *
 * All rights reserved
 */

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use demosplan\DemosPlanCoreBundle\Entity\PlatformFaq;
use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id {@link PlatformFaq::id}
 * @property-read End $title {@link PlatformFaq::title}
 * @property-read End $text {@link PlatformFaq::text}
 * @property-read End $enabled {@link PlatformFaq::enabled}
 * @property-read End $createDate {@link PlatformFaq::createDate}
 * @property-read End $modifyDate {@link PlatformFaq::modifyDate}
 * @property-read RolePath $roles {@link PlatformFaq::roles}
 * @property-read PlatformFaqCategoryPath $platformFaqCategory {@link PlatformFaq::platformFaqCategory}
 */
class PlatformFaqPath implements PropertyAutoPathInterface
{
    use PropertyAutoPathTrait;
}
