<?php

declare(strict_types=1);

/**
 * This file is part of the package demosplan.
 *
 * (c) 2010-present DEMOS plan GmbH, for more information see the license file.
 *
 * All rights reserved
 */

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use demosplan\DemosPlanCoreBundle\Entity\Procedure\ProcedureType;
use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id {@link ProcedureType::id}
 * @property-read End $creationDate {@link ProcedureType::creationDate}
 * @property-read End $modificationDate {@link ProcedureType::modificationDate}
 * @property-read ProcedurePath $procedures {@link ProcedureType::procedures}
 * @property-read End $name {@link ProcedureType::name}
 * @property-read End $description {@link ProcedureType::description}
 * @property-read StatementFormDefinitionPath $statementFormDefinition {@link ProcedureType::statementFormDefinition}
 * @property-read ProcedureBehaviorDefinitionPath $procedureBehaviorDefinition {@link ProcedureType::procedureBehaviorDefinition}
 * @property-read ProcedureUiDefinitionPath $procedureUiDefinition {@link ProcedureType::procedureUiDefinition}
 */
class ProcedureTypePath implements PropertyAutoPathInterface
{
    use PropertyAutoPathTrait;
}
