<?php

declare(strict_types=1);

/**
 * This file is part of the package demosplan.
 *
 * (c) 2010-present DEMOS plan GmbH, for more information see the license file.
 *
 * All rights reserved
 */

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use demosplan\DemosPlanCoreBundle\Entity\Procedure\Procedure;
use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id {@link Procedure::id}
 * @property-read End $name {@link Procedure::name}
 * @property-read End $shortUrl {@link Procedure::shortUrl}
 * @property-read End $orgaName {@link Procedure::orgaName}
 * @property-read OrgaPath $orga {@link Procedure::orga}
 * @property-read End $desc {@link Procedure::desc}
 * @property-read End $phase {@link Procedure::phase}
 * @property-read End $step {@link Procedure::step}
 * @property-read End $logo {@link Procedure::logo}
 * @property-read End $externId {@link Procedure::externId}
 * @property-read End $plisId {@link Procedure::plisId}
 * @property-read End $closed {@link Procedure::closed}
 * @property-read End $deleted {@link Procedure::deleted}
 * @property-read End $master {@link Procedure::master}
 * @property-read End $masterTemplate {@link Procedure::masterTemplate}
 * @property-read End $externalName {@link Procedure::externalName}
 * @property-read End $externalDesc {@link Procedure::externalDesc}
 * @property-read End $publicParticipation {@link Procedure::publicParticipation}
 * @property-read End $publicParticipationPhase {@link Procedure::publicParticipationPhase}
 * @property-read End $publicParticipationStep {@link Procedure::publicParticipationStep}
 * @property-read End $publicParticipationStartDate {@link Procedure::publicParticipationStartDate}
 * @property-read End $publicParticipationEndDate {@link Procedure::publicParticipationEndDate}
 * @property-read End $publicParticipationContact {@link Procedure::publicParticipationContact}
 * @property-read End $publicParticipationPublicationEnabled {@link Procedure::publicParticipationPublicationEnabled}
 * @property-read End $locationName {@link Procedure::locationName}
 * @property-read End $locationPostCode {@link Procedure::locationPostCode}
 * @property-read End $municipalCode {@link Procedure::municipalCode}
 * @property-read End $ars {@link Procedure::ars}
 * @property-read End $createdDate {@link Procedure::createdDate}
 * @property-read End $startDate {@link Procedure::startDate}
 * @property-read End $endDate {@link Procedure::endDate}
 * @property-read End $closedDate {@link Procedure::closedDate}
 * @property-read End $deletedDate {@link Procedure::deletedDate}
 * @property-read OrgaPath $organisation {@link Procedure::organisation}
 * @property-read OrgaPath $planningOffices {@link Procedure::planningOffices}
 * @property-read OrgaPath $dataInputOrganisations {@link Procedure::dataInputOrganisations}
 * @property-read ProcedureSettingsPath $settings {@link Procedure::settings}
 * @property-read TagTopicPath $topics {@link Procedure::topics}
 * @property-read NotificationReceiverPath $notificationReceivers {@link Procedure::notificationReceivers}
 * @property-read ElementsPath $elements {@link Procedure::elements}
 * @property-read UserPath $authorizedUsers {@link Procedure::authorizedUsers}
 * @property-read End $agencyMainEmailAddress {@link Procedure::agencyMainEmailAddress}
 * @property-read EmailAddressPath $agencyExtraEmailAddresses {@link Procedure::agencyExtraEmailAddresses}
 * @property-read CustomerPath $customer {@link Procedure::customer}
 * @property-read ProcedureCategoryPath $procedureCategories {@link Procedure::procedureCategories}
 * @property-read StatementPath $statements {@link Procedure::statements}
 * @property-read SurveyPath $surveys {@link Procedure::surveys}
 * @property-read ProcedureTypePath $procedureType {@link Procedure::procedureType}
 * @property-read StatementFormDefinitionPath $statementFormDefinition {@link Procedure::statementFormDefinition}
 * @property-read ProcedureBehaviorDefinitionPath $procedureBehaviorDefinition {@link Procedure::procedureBehaviorDefinition}
 * @property-read ProcedureUiDefinitionPath $procedureUiDefinition {@link Procedure::procedureUiDefinition}
 * @property-read ExportFieldsConfigurationPath $exportFieldsConfigurations {@link Procedure::exportFieldsConfigurations}
 * @property-read FilePath $files {@link Procedure::files}
 * @property-read End $xtaPlanId {@link Procedure::xtaPlanId}
 * @property-read PlacePath $segmentPlaces {@link Procedure::segmentPlaces}
 * @property-read SlugPath $currentSlug {@link Procedure::currentSlug}
 * @property-read SlugPath $slugs {@link Procedure::slugs}
 */
class ProcedurePath implements PropertyAutoPathInterface
{
    use PropertyAutoPathTrait;
}
