<?php

declare(strict_types=1);

/**
 * This file is part of the package demosplan.
 *
 * (c) 2010-present DEMOS plan GmbH, for more information see the license file.
 *
 * All rights reserved
 */

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use demosplan\DemosPlanCoreBundle\Entity\Procedure\ProcedureSubscription;
use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $ident {@link ProcedureSubscription::ident}
 * @property-read UserPath $user {@link ProcedureSubscription::user}
 * @property-read End $userEmail {@link ProcedureSubscription::userEmail}
 * @property-read End $postcode {@link ProcedureSubscription::postcode}
 * @property-read End $city {@link ProcedureSubscription::city}
 * @property-read End $distance {@link ProcedureSubscription::distance}
 * @property-read End $deleted {@link ProcedureSubscription::deleted}
 * @property-read End $createdDate {@link ProcedureSubscription::createdDate}
 * @property-read End $modifiedDate {@link ProcedureSubscription::modifiedDate}
 * @property-read End $deletedDate {@link ProcedureSubscription::deletedDate}
 */
class ProcedureSubscriptionPath implements PropertyAutoPathInterface
{
    use PropertyAutoPathTrait;
}
