<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;
use demosplan\DemosPlanCoreBundle\Entity\Procedure\ProcedureCategory;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id {@link ProcedureCategory::id}
 * @property-read End $name {@link ProcedureCategory::name}
 * @property-read End $slug {@link ProcedureCategory::slug}
 */
class ProcedureCategoryPath implements PropertyAutoPathInterface
{
	use PropertyAutoPathTrait;
}
