<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;
use demosplan\DemosPlanCoreBundle\Entity\Procedure\ProcedureUiDefinition;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id {@link ProcedureUiDefinition::id}
 * @property-read End $creationDate {@link ProcedureUiDefinition::creationDate}
 * @property-read End $modificationDate {@link ProcedureUiDefinition::modificationDate}
 * @property-read ProcedurePath $procedure {@link ProcedureUiDefinition::procedure}
 * @property-read ProcedureTypePath $procedureType {@link ProcedureUiDefinition::procedureType}
 * @property-read End $mapHintDefault {@link ProcedureUiDefinition::mapHintDefault}
 * @property-read End $statementFormHintStatement {@link ProcedureUiDefinition::statementFormHintStatement}
 * @property-read End $statementFormHintPersonalData {@link ProcedureUiDefinition::statementFormHintPersonalData}
 * @property-read End $statementFormHintRecheck {@link ProcedureUiDefinition::statementFormHintRecheck}
 * @property-read End $statementPublicSubmitConfirmationText {@link ProcedureUiDefinition::statementPublicSubmitConfirmationText}
 */
class ProcedureUiDefinitionPath implements PropertyAutoPathInterface
{
	use PropertyAutoPathTrait;
}
