<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;
use demosplan\DemosPlanCoreBundle\Entity\Procedure\ProcedureProposal;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id {@link ProcedureProposal::id}
 * @property-read End $name {@link ProcedureProposal::name}
 * @property-read End $description {@link ProcedureProposal::description}
 * @property-read End $createdDate {@link ProcedureProposal::createdDate}
 * @property-read End $modifiedDate {@link ProcedureProposal::modifiedDate}
 * @property-read End $additionalExplanation {@link ProcedureProposal::additionalExplanation}
 * @property-read End $coordinate {@link ProcedureProposal::coordinate}
 * @property-read UserPath $user {@link ProcedureProposal::user}
 * @property-read End $status {@link ProcedureProposal::status}
 * @property-read FilePath $files {@link ProcedureProposal::files}
 */
class ProcedureProposalPath implements PropertyAutoPathInterface
{
	use PropertyAutoPathTrait;
}
