<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;
use demosplan\DemosPlanCoreBundle\Entity\Report\ReportEntry;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id {@link ReportEntry::id}
 * @property-read End $category {@link ReportEntry::category}
 * @property-read End $group {@link ReportEntry::group}
 * @property-read End $level {@link ReportEntry::level}
 * @property-read End $userId {@link ReportEntry::userId}
 * @property-read End $userName {@link ReportEntry::userName}
 * @property-read End $sessionId {@link ReportEntry::sessionId}
 * @property-read End $identifierType {@link ReportEntry::identifierType}
 * @property-read End $identifier {@link ReportEntry::identifier}
 * @property-read End $mimeType {@link ReportEntry::mimeType}
 * @property-read End $message {@link ReportEntry::message}
 * @property-read End $incoming {@link ReportEntry::incoming}
 * @property-read End $createDate {@link ReportEntry::createDate}
 * @property-read CustomerPath $customer {@link ReportEntry::customer}
 */
class ReportEntryPath implements PropertyAutoPathInterface
{
	use PropertyAutoPathTrait;
}
