<?php

declare(strict_types=1);

/**
 * This file is part of the package demosplan.
 *
 * (c) 2010-present DEMOS plan GmbH, for more information see the license file.
 *
 * All rights reserved
 */

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use demosplan\DemosPlanCoreBundle\Entity\User\Role;
use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $ident {@link Role::ident}
 * @property-read End $code {@link Role::code}
 * @property-read End $groupCode {@link Role::groupCode}
 * @property-read End $groupName {@link Role::groupName}
 * @property-read UserRoleInCustomerPath $userRoleInCustomers {@link Role::userRoleInCustomers}
 */
class RolePath implements PropertyAutoPathInterface
{
    use PropertyAutoPathTrait;
}
