<?php

declare(strict_types=1);

/**
 * This file is part of the package demosplan.
 *
 * (c) 2010-present DEMOS plan GmbH, for more information see the license file.
 *
 * All rights reserved
 */

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use demosplan\DemosPlanCoreBundle\Entity\Statement\SegmentComment;
use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id {@link SegmentComment::id}
 * @property-read SegmentPath $segment {@link SegmentComment::segment}
 * @property-read UserPath $submitter {@link SegmentComment::submitter}
 * @property-read PlacePath $place {@link SegmentComment::place}
 * @property-read End $creationDate {@link SegmentComment::creationDate}
 * @property-read End $text {@link SegmentComment::text}
 */
class SegmentCommentPath implements PropertyAutoPathInterface
{
    use PropertyAutoPathTrait;
}
