<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;
use demosplan\DemosPlanCoreBundle\Entity\Sessions;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $sess_id {@link Sessions::sess_id}
 * @property-read End $sess_data {@link Sessions::sess_data}
 * @property-read End $sess_lifetime {@link Sessions::sess_lifetime}
 * @property-read End $sess_time {@link Sessions::sess_time}
 */
class SessionsPath implements PropertyAutoPathInterface
{
	use PropertyAutoPathTrait;
}
