<?php

declare(strict_types=1);

/**
 * This file is part of the package demosplan.
 *
 * (c) 2010-present DEMOS plan GmbH, for more information see the license file.
 *
 * All rights reserved
 */

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use demosplan\DemosPlanCoreBundle\Entity\Setting;
use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $ident {@link Setting::ident}
 * @property-read ProcedurePath $procedure {@link Setting::procedure}
 * @property-read UserPath $user {@link Setting::user}
 * @property-read OrgaPath $orga {@link Setting::orga}
 * @property-read End $orgaId {@link Setting::orgaId}
 * @property-read End $key {@link Setting::key}
 * @property-read End $content {@link Setting::content}
 * @property-read End $created {@link Setting::created}
 * @property-read End $modified {@link Setting::modified}
 */
class SettingPath implements PropertyAutoPathInterface
{
    use PropertyAutoPathTrait;
}
