<?php

declare(strict_types=1);

/**
 * This file is part of the package demosplan.
 *
 * (c) 2010-present DEMOS plan GmbH, for more information see the license file.
 *
 * All rights reserved
 */

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use demosplan\DemosPlanCoreBundle\Entity\Document\SingleDocumentVersion;
use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id {@link SingleDocumentVersion::id}
 * @property-read SingleDocumentPath $singleDocument {@link SingleDocumentVersion::singleDocument}
 * @property-read ProcedurePath $procedure {@link SingleDocumentVersion::procedure}
 * @property-read ElementsPath $element {@link SingleDocumentVersion::element}
 * @property-read End $category {@link SingleDocumentVersion::category}
 * @property-read End $order {@link SingleDocumentVersion::order}
 * @property-read End $title {@link SingleDocumentVersion::title}
 * @property-read End $text {@link SingleDocumentVersion::text}
 * @property-read End $symbol {@link SingleDocumentVersion::symbol}
 * @property-read End $document {@link SingleDocumentVersion::document}
 * @property-read End $statementEnabled {@link SingleDocumentVersion::statementEnabled}
 * @property-read End $visible {@link SingleDocumentVersion::visible}
 * @property-read End $deleted {@link SingleDocumentVersion::deleted}
 * @property-read End $versionDate {@link SingleDocumentVersion::versionDate}
 * @property-read End $createDate {@link SingleDocumentVersion::createDate}
 * @property-read End $modifyDate {@link SingleDocumentVersion::modifyDate}
 * @property-read End $deleteDate {@link SingleDocumentVersion::deleteDate}
 */
class SingleDocumentVersionPath implements PropertyAutoPathInterface
{
    use PropertyAutoPathTrait;
}
