<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;
use demosplan\DemosPlanCoreBundle\Entity\Document\SingleDocument;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id {@link SingleDocument::id}
 * @property-read ProcedurePath $procedure {@link SingleDocument::procedure}
 * @property-read ElementsPath $element {@link SingleDocument::element}
 * @property-read End $category {@link SingleDocument::category}
 * @property-read End $order {@link SingleDocument::order}
 * @property-read End $title {@link SingleDocument::title}
 * @property-read End $text {@link SingleDocument::text}
 * @property-read End $symbol {@link SingleDocument::symbol}
 * @property-read End $document {@link SingleDocument::document}
 * @property-read End $statementEnabled {@link SingleDocument::statementEnabled}
 * @property-read End $visible {@link SingleDocument::visible}
 * @property-read End $deleted {@link SingleDocument::deleted}
 * @property-read End $createDate {@link SingleDocument::createDate}
 * @property-read End $modifyDate {@link SingleDocument::modifyDate}
 * @property-read End $deleteDate {@link SingleDocument::deleteDate}
 * @property-read SingleDocumentVersionPath $versions {@link SingleDocument::versions}
 */
class SingleDocumentPath implements PropertyAutoPathInterface
{
	use PropertyAutoPathTrait;
}
