<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;
use demosplan\DemosPlanCoreBundle\Entity\Statement\StatementAttribute;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id {@link StatementAttribute::id}
 * @property-read StatementPath $statement {@link StatementAttribute::statement}
 * @property-read DraftStatementPath $draftStatement {@link StatementAttribute::draftStatement}
 * @property-read End $type {@link StatementAttribute::type}
 * @property-read End $value {@link StatementAttribute::value}
 */
class StatementAttributePath implements PropertyAutoPathInterface
{
	use PropertyAutoPathTrait;
}
