<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;
use demosplan\DemosPlanCoreBundle\Entity\Procedure\StatementFieldDefinition;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id {@link StatementFieldDefinition::id}
 * @property-read End $creationDate {@link StatementFieldDefinition::creationDate}
 * @property-read End $modificationDate {@link StatementFieldDefinition::modificationDate}
 * @property-read End $name {@link StatementFieldDefinition::name}
 * @property-read StatementFormDefinitionPath $statementFormDefinition {@link StatementFieldDefinition::statementFormDefinition}
 * @property-read End $orderNumber {@link StatementFieldDefinition::orderNumber}
 * @property-read End $enabled {@link StatementFieldDefinition::enabled}
 * @property-read End $required {@link StatementFieldDefinition::required}
 */
class StatementFieldDefinitionPath implements PropertyAutoPathInterface
{
	use PropertyAutoPathTrait;
}
