<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;
use demosplan\DemosPlanCoreBundle\Entity\StatementAttachment;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id {@link StatementAttachment::id}
 * @property-read FilePath $file {@link StatementAttachment::file}
 * @property-read End $type {@link StatementAttachment::type}
 * @property-read StatementPath $statement {@link StatementAttachment::statement}
 */
class StatementAttachmentPath implements PropertyAutoPathInterface
{
	use PropertyAutoPathTrait;
}
