<?php

declare(strict_types=1);

/**
 * This file is part of the package demosplan.
 *
 * (c) 2010-present DEMOS plan GmbH, for more information see the license file.
 *
 * All rights reserved
 */

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use demosplan\DemosPlanCoreBundle\Entity\Statement\StatementVote;
use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id {@link StatementVote::id}
 * @property-read StatementPath $statement {@link StatementVote::statement}
 * @property-read UserPath $user {@link StatementVote::user}
 * @property-read End $firstName {@link StatementVote::firstName}
 * @property-read End $lastName {@link StatementVote::lastName}
 * @property-read End $active {@link StatementVote::active}
 * @property-read End $deleted {@link StatementVote::deleted}
 * @property-read End $createdDate {@link StatementVote::createdDate}
 * @property-read End $modifiedDate {@link StatementVote::modifiedDate}
 * @property-read End $deletedDate {@link StatementVote::deletedDate}
 * @property-read End $manual {@link StatementVote::manual}
 * @property-read End $createdByCitizen {@link StatementVote::createdByCitizen}
 * @property-read End $organisationName {@link StatementVote::organisationName}
 * @property-read End $departmentName {@link StatementVote::departmentName}
 * @property-read End $userName {@link StatementVote::userName}
 * @property-read End $userMail {@link StatementVote::userMail}
 * @property-read End $userPostcode {@link StatementVote::userPostcode}
 * @property-read End $userCity {@link StatementVote::userCity}
 */
class StatementVotePath implements PropertyAutoPathInterface
{
    use PropertyAutoPathTrait;
}
