<?php

declare(strict_types=1);

/**
 * This file is part of the package demosplan.
 *
 * (c) 2010-present DEMOS plan GmbH, for more information see the license file.
 *
 * All rights reserved
 */

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use demosplan\DemosPlanCoreBundle\Entity\Statement\StatementMeta;
use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id {@link StatementMeta::id}
 * @property-read StatementPath $statement {@link StatementMeta::statement}
 * @property-read End $authorName {@link StatementMeta::authorName}
 * @property-read End $authorFeedback {@link StatementMeta::authorFeedback}
 * @property-read End $submitUId {@link StatementMeta::submitUId}
 * @property-read End $submitName {@link StatementMeta::submitName}
 * @property-read End $orgaName {@link StatementMeta::orgaName}
 * @property-read End $orgaDepartmentName {@link StatementMeta::orgaDepartmentName}
 * @property-read End $caseWorkerName {@link StatementMeta::caseWorkerName}
 * @property-read End $orgaStreet {@link StatementMeta::orgaStreet}
 * @property-read End $houseNumber {@link StatementMeta::houseNumber}
 * @property-read End $orgaPostalCode {@link StatementMeta::orgaPostalCode}
 * @property-read End $orgaCity {@link StatementMeta::orgaCity}
 * @property-read End $orgaEmail {@link StatementMeta::orgaEmail}
 * @property-read End $authoredDate {@link StatementMeta::authoredDate}
 * @property-read End $submitOrgaId {@link StatementMeta::submitOrgaId}
 * @property-read End $miscData {@link StatementMeta::miscData}
 */
class StatementMetaPath implements PropertyAutoPathInterface
{
    use PropertyAutoPathTrait;
}
