<?php

declare(strict_types=1);

/**
 * This file is part of the package demosplan.
 *
 * (c) 2010-present DEMOS plan GmbH, for more information see the license file.
 *
 * All rights reserved
 */

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use demosplan\DemosPlanCoreBundle\Entity\Statement\StatementFragment;
use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id {@link StatementFragment::id}
 * @property-read StatementPath $statement {@link StatementFragment::statement}
 * @property-read End $displayId {@link StatementFragment::displayId}
 * @property-read End $text {@link StatementFragment::text}
 * @property-read TagPath $tags {@link StatementFragment::tags}
 * @property-read ProcedurePath $procedure {@link StatementFragment::procedure}
 * @property-read End $voteAdvice {@link StatementFragment::voteAdvice}
 * @property-read End $vote {@link StatementFragment::vote}
 * @property-read End $created {@link StatementFragment::created}
 * @property-read End $modified {@link StatementFragment::modified}
 * @property-read End $assignedToFbDate {@link StatementFragment::assignedToFbDate}
 * @property-read DepartmentPath $department {@link StatementFragment::department}
 * @property-read End $considerationAdvice {@link StatementFragment::considerationAdvice}
 * @property-read End $consideration {@link StatementFragment::consideration}
 * @property-read CountyPath $counties {@link StatementFragment::counties}
 * @property-read PriorityAreaPath $priorityAreas {@link StatementFragment::priorityAreas}
 * @property-read MunicipalityPath $municipalities {@link StatementFragment::municipalities}
 * @property-read DepartmentPath $archivedDepartment {@link StatementFragment::archivedDepartment}
 * @property-read End $archivedOrgaName {@link StatementFragment::archivedOrgaName}
 * @property-read End $archivedDepartmentName {@link StatementFragment::archivedDepartmentName}
 * @property-read End $archivedVoteUserName {@link StatementFragment::archivedVoteUserName}
 * @property-read UserPath $assignee {@link StatementFragment::assignee}
 * @property-read StatementFragmentVersionPath $versions {@link StatementFragment::versions}
 * @property-read End $sortIndex {@link StatementFragment::sortIndex}
 * @property-read UserPath $modifiedByUser {@link StatementFragment::modifiedByUser}
 * @property-read DepartmentPath $modifiedByDepartment {@link StatementFragment::modifiedByDepartment}
 * @property-read End $status {@link StatementFragment::status}
 * @property-read UserPath $lastClaimed {@link StatementFragment::lastClaimed}
 * @property-read ElementsPath $element {@link StatementFragment::element}
 * @property-read ParagraphVersionPath $paragraph {@link StatementFragment::paragraph}
 * @property-read SingleDocumentVersionPath $document {@link StatementFragment::document}
 */
class StatementFragmentPath implements PropertyAutoPathInterface
{
    use PropertyAutoPathTrait;
}
