<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;
use demosplan\DemosPlanCoreBundle\Entity\Procedure\StatementFormDefinition;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id {@link StatementFormDefinition::id}
 * @property-read End $creationDate {@link StatementFormDefinition::creationDate}
 * @property-read End $modificationDate {@link StatementFormDefinition::modificationDate}
 * @property-read StatementFieldDefinitionPath $fieldDefinitions {@link StatementFormDefinition::fieldDefinitions}
 * @property-read ProcedurePath $procedure {@link StatementFormDefinition::procedure}
 * @property-read ProcedureTypePath $procedureType {@link StatementFormDefinition::procedureType}
 */
class StatementFormDefinitionPath implements PropertyAutoPathInterface
{
	use PropertyAutoPathTrait;
}
