<?php

declare(strict_types=1);

/**
 * This file is part of the package demosplan.
 *
 * (c) 2010-present DEMOS plan GmbH, for more information see the license file.
 *
 * All rights reserved
 */

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use demosplan\DemosPlanCoreBundle\Entity\Statement\StatementVersionField;
use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id {@link StatementVersionField::id}
 * @property-read End $userIdent {@link StatementVersionField::userIdent}
 * @property-read End $userName {@link StatementVersionField::userName}
 * @property-read End $sessionIdent {@link StatementVersionField::sessionIdent}
 * @property-read End $name {@link StatementVersionField::name}
 * @property-read End $type {@link StatementVersionField::type}
 * @property-read End $value {@link StatementVersionField::value}
 * @property-read End $created {@link StatementVersionField::created}
 * @property-read StatementPath $statement {@link StatementVersionField::statement}
 */
class StatementVersionFieldPath implements PropertyAutoPathInterface
{
    use PropertyAutoPathTrait;
}
