<?php

declare(strict_types=1);

/**
 * This file is part of the package demosplan.
 *
 * (c) 2010-present DEMOS plan GmbH, for more information see the license file.
 *
 * All rights reserved
 */

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use demosplan\DemosPlanCoreBundle\Entity\User\SupportContact;
use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id {@link SupportContact::id}
 * @property-read End $title {@link SupportContact::title}
 * @property-read End $phoneNumber {@link SupportContact::phoneNumber}
 * @property-read EmailAddressPath $eMailAddress {@link SupportContact::eMailAddress}
 * @property-read End $text {@link SupportContact::text}
 * @property-read End $visible {@link SupportContact::visible}
 * @property-read CustomerPath $customer {@link SupportContact::customer}
 * @property-read End $supportType {@link SupportContact::supportType}
 * @property-read End $createdAt {@link SupportContact::createdAt}
 * @property-read End $updatedAt {@link SupportContact::updatedAt}
 */
class SupportContactPath implements PropertyAutoPathInterface
{
    use PropertyAutoPathTrait;
}
