<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;
use demosplan\DemosPlanCoreBundle\Entity\Survey\SurveyVote;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id {@link SurveyVote::id}
 * @property-read End $isAgreed {@link SurveyVote::isAgreed}
 * @property-read End $text {@link SurveyVote::text}
 * @property-read End $textReview {@link SurveyVote::textReview}
 * @property-read End $createdDate {@link SurveyVote::createdDate}
 * @property-read SurveyPath $survey {@link SurveyVote::survey}
 * @property-read UserPath $user {@link SurveyVote::user}
 */
class SurveyVotePath implements PropertyAutoPathInterface
{
	use PropertyAutoPathTrait;
}
