<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;
use demosplan\DemosPlanCoreBundle\Entity\Survey\Survey;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id {@link Survey::id}
 * @property-read End $title {@link Survey::title}
 * @property-read End $description {@link Survey::description}
 * @property-read End $startDate {@link Survey::startDate}
 * @property-read End $endDate {@link Survey::endDate}
 * @property-read End $status {@link Survey::status}
 * @property-read ProcedurePath $procedure {@link Survey::procedure}
 * @property-read SurveyVotePath $votes {@link Survey::votes}
 */
class SurveyPath implements PropertyAutoPathInterface
{
	use PropertyAutoPathTrait;
}
