<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;
use demosplan\DemosPlanCoreBundle\Entity\Statement\Tag;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id {@link Tag::id}
 * @property-read TagTopicPath $topic {@link Tag::topic}
 * @property-read End $title {@link Tag::title}
 * @property-read End $createDate {@link Tag::createDate}
 * @property-read StatementPath $statements {@link Tag::statements}
 * @property-read BoilerplatePath $boilerplate {@link Tag::boilerplate}
 */
class TagPath implements PropertyAutoPathInterface
{
	use PropertyAutoPathTrait;
}
