<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;
use demosplan\DemosPlanCoreBundle\Entity\Statement\TagTopic;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id {@link TagTopic::id}
 * @property-read End $title {@link TagTopic::title}
 * @property-read End $createDate {@link TagTopic::createDate}
 * @property-read ProcedurePath $procedure {@link TagTopic::procedure}
 * @property-read TagPath $tags {@link TagTopic::tags}
 */
class TagTopicPath implements PropertyAutoPathInterface
{
	use PropertyAutoPathTrait;
}
