<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;
use demosplan\DemosPlanCoreBundle\Entity\Procedure\UserFilterSet;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id {@link UserFilterSet::id}
 * @property-read UserPath $user {@link UserFilterSet::user}
 * @property-read End $name {@link UserFilterSet::name}
 * @property-read HashedQueryPath $filterSet {@link UserFilterSet::filterSet}
 * @property-read ProcedurePath $procedure {@link UserFilterSet::procedure}
 */
class UserFilterSetPath implements PropertyAutoPathInterface
{
	use PropertyAutoPathTrait;
}
