<?php

declare(strict_types=1);

/**
 * This file is part of the package demosplan.
 *
 * (c) 2010-present DEMOS plan GmbH, for more information see the license file.
 *
 * All rights reserved
 */

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use demosplan\DemosPlanCoreBundle\Entity\User\UserRoleInCustomer;
use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id {@link UserRoleInCustomer::id}
 * @property-read UserPath $user {@link UserRoleInCustomer::user}
 * @property-read RolePath $role {@link UserRoleInCustomer::role}
 * @property-read CustomerPath $customer {@link UserRoleInCustomer::customer}
 */
class UserRoleInCustomerPath implements PropertyAutoPathInterface
{
    use PropertyAutoPathTrait;
}
