<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;
use demosplan\DemosPlanCoreBundle\Entity\User\User;
use demosplan\DemosPlanCoreBundle\EntityPath\UserPath as UserPath1;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id {@link User::id}
 * @property-read End $dmId {@link User::dmId}
 * @property-read End $gender {@link User::gender}
 * @property-read End $title {@link User::title}
 * @property-read End $firstname {@link User::firstname}
 * @property-read End $lastname {@link User::lastname}
 * @property-read End $email {@link User::email}
 * @property-read End $login {@link User::login}
 * @property-read End $password {@link User::password}
 * @property-read End $alternativeLoginPassword {@link User::alternativeLoginPassword}
 * @property-read End $salt {@link User::salt}
 * @property-read End $language {@link User::language}
 * @property-read End $createdDate {@link User::createdDate}
 * @property-read End $modifiedDate {@link User::modifiedDate}
 * @property-read End $lastLogin {@link User::lastLogin}
 * @property-read End $deleted {@link User::deleted}
 * @property-read End $gwId {@link User::gwId}
 * @property-read End $flags {@link User::flags}
 * @property-read OrgaPath $orga {@link User::orga}
 * @property-read DepartmentPath $departments {@link User::departments}
 * @property-read UserRoleInCustomerPath $roleInCustomers {@link User::roleInCustomers}
 * @property-read AddressPath $addresses {@link User::addresses}
 * @property-read SurveyVotePath $surveyVotes {@link User::surveyVotes}
 * @property-read UserPath $twinUser {@link User::twinUser}
 * @property-read ProcedurePath $authorizedProcedures {@link User::authorizedProcedures}
 * @property-read End $providedByIdentityProvider {@link User::providedByIdentityProvider}
 */
class UserPath implements PropertyAutoPathInterface
{
	use PropertyAutoPathTrait;
}
