<?php

declare(strict_types=1);

namespace demosplan\DemosPlanCoreBundle\EntityPath;

use EDT\PathBuilding\End;
use EDT\PathBuilding\PropertyAutoPathInterface;
use EDT\PathBuilding\PropertyAutoPathTrait;
use demosplan\DemosPlanCoreBundle\Entity\Video;

/**
 * WARNING: THIS CLASS IS AUTOGENERATED.
 * MANUAL CHANGES WILL BE LOST ON RE-GENERATION.
 *
 * To add additional properties, you may want to
 * create an extending class and add them there.
 *
 * @property-read End $id {@link Video::id}
 * @property-read End $creationDate {@link Video::creationDate}
 * @property-read End $modificationDate {@link Video::modificationDate}
 * @property-read UserPath $uploader {@link Video::uploader}
 * @property-read CustomerPath $customerContext {@link Video::customerContext}
 * @property-read FilePath $file {@link Video::file}
 * @property-read End $title {@link Video::title}
 * @property-read End $description {@link Video::description}
 */
class VideoPath implements PropertyAutoPathInterface
{
	use PropertyAutoPathTrait;
}
