doctrine:
    dbal:
        default_connection: dplan
        connections:
            dplan:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
            dplan_install:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_install_user%"
                password: "%database_install_password%"
                charset:  UTF8
        types:
            dplan.stored_query: \demosplan\DemosPlanCoreBundle\Doctrine\Type\StoredQueryType

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        default_entity_manager: default
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                connection: dplan
                auto_mapping: true
                metadata_cache_driver:
                    type: pool
                    pool: doctrine.cache_pool
                query_cache_driver:
                    type: pool
                    pool: doctrine.cache_pool
            install:
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                connection: dplan_install
