hslavich_onelogin_saml:
    # Basic settings
    idp:
        entityId: '%saml_idp_entityid%'
        singleSignOnService:
            url: '%saml_idp_sso_url%'
            binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
        singleLogoutService:
            url: '%saml_idp_slo_url%'
            binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
        x509cert: '%saml_idp_x509_string%'
    sp:
        entityId: '%saml_sp_entityid%'
        assertionConsumerService:
            url: '%saml_sp_acs_url%'
            binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST'
        singleLogoutService:
            url: '%saml_sp_sls_url%'
            binding: 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
        x509cert: '%saml_sp_x509_string%'
        privateKey: '%saml_sp_x509_private_string%'
    # Optional settings
    baseurl: '%saml_baseurl%'
    strict: false
    debug: false
    security:
        nameIdEncrypted:       true
        authnRequestsSigned:   true
        logoutRequestSigned:   true
        logoutResponseSigned:  true
        wantMessagesSigned:    true
        wantAssertionsSigned:  true
        wantNameIdEncrypted:   false
        requestedAuthnContext: false
        signMetadata: true
        wantXMLValidation: true
        signatureAlgorithm: 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256'
        digestAlgorithm: 'http://www.w3.org/2001/04/xmlenc#sha256'
