# /etc/zsh/zshenv: system-wide .zshenv file for zsh(1).
#
# This file is sourced on all invocations of the shell.
# If the -f flag is present or if the NO_RCS option is
# set within this file, all other initialization files
# are skipped.
#
# This file should contain commands to set the command
# search path, plus other important environment variables.
# This file should not contain commands that produce
# output or assume the shell is attached to a tty.
#
# Global Order: zshenv, zprofile, zshrc, zlogin

if [[ -z "$PATH" || "$PATH" == "/bin:/usr/bin" ]]
then
	export PATH="/usr/local/bin:/usr/bin:/bin"
fi

function php-xdbg() {
    PHP_IDE_CONFIG="serverName=172.22.255.2" php -dzend_extension=xdebug.so \
        -dxdebug.mode=debug \
        -dxdebug.start_with_request=yes \
        -dxdebug.client_host=172.22.255.1 \
        $@
}

function plogs()
{
	lnav /tmp/dplan/$1/logs/prod/*.log
}

function dlogs()
{
	lnav /tmp/dplan/$1/logs/dev/\*.log
}

function tlogs()
{
	lnav /tmp/dplan/$1/logs/test/\*.log
}

alias c=composer
alias y=yarn

alias php-xdebug=php-xdbg
alias phpdbg=php-xdbg

alias phpunit="/srv/www/vendor/bin/phpunit"
alias php-cs-fixer="/srv/www/vendor/bin/php-cs-fixer"
alias phpstan="/srv/www/bin/blp dplan:phpstan"
alias psalm="/srv/www/bin/blp dplan:psalm"

alias fe=/srv/www/fe

# general setup
setopt autocd # implicitly cd into dir if prompt is existing dir
setopt beep # don't beep, i know, confusing option name
setopt extendedglob # match more stuff, this enables nested {}-expansion
setopt nomatch # don't glob match inside quoted command arguments and report none matching globs
setopt notify # report the status of background jobs immediately
setopt prompt_subst # enable prompt substitution with input if input is longer than $COLS

export REPORTTIME=10 # seconds after which process execution duration is reported

# history config
setopt hist_ignore_all_dups # remove any duplicates from the history
setopt hist_no_store # don't track calls to the `history` / `fc -l` commands reading the history
setopt share_history # share history between all current sessions, this also auto-writes history

export HISTFILE=~/.zsh_history # store the zsh history relative to the users' home
export SAVEHIST=10000 # number of lines in the history file
export HISTSIZE=10000 # number of lines in the history buffer

bindkey -e

PROMPT='%(?..%B%F{red}%?%f%b )%n@%2m:%B%1~%(!.%F{red}>%f.%F{green}>%f)%b '

export DEVELOPMENT_CONTAINER="1"
