name: CI Checks

on:
  pull_request:
    paths:
      - '**.php'
      - '**.js'
      - '**.vue'

jobs:
  cancel:
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.12.1
        with:
          workflow_id: "ci-checks"
          access_token: ${{ secrets.GITHUB_TOKEN }}

  code-quality:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP with composer v2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: gd soap sockets zip
          tools: composer:v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '20.18.1'
          cache: 'yarn'

      - name: Cache php modules
        uses: actions/cache@v4.2.3
        with:
          path: |
            ~/.composer/cache
            vendor
          key: ${{ runner.os }}-build-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-php-${{ hashFiles('**/composer.lock') }}

      - name: Miscellaneous runtime caches
        uses: actions/cache@v4.2.3
        with:
          path: |
            config/.runtime/cache
          key: ${{ runner.os }}-infrastructure-runtime
          restore-keys: |
            ${{ runner.os }}-infrastructure-runtime

      - name: Install composer dependencies
        run: |
          composer --version
          composer install --no-interaction

      - name: Install Node.js dependencies
        run: yarn install

      - name: Warmup cache
        run: DEVELOPMENT_CONTAINER=1 php bin/test cache:clear

      - name: Run ESLint
        run: yarn lint

      - name: Run PHPStan
        run: DEVELOPMENT_CONTAINER=1 php bin/test dplan:phpstan --ci -l1