name: Run FE_headerWriter

on:
  pull_request:
    paths:
      - '**.scss'
      - '**.js'
      - '**.vue'

jobs:
  cancel:
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
        -   uses: styfle/cancel-workflow-action@0.10.0
            with:
                workflow_id: "FE_headerWriter"
                access_token: ${{ secrets.GITHUB_TOKEN }}

  FE_headerWriter:
    runs-on: ubuntu-20.04
    steps:

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: download headerWriter
        run: |
         wget --header "Authorization: Token ${{ secrets.DEMOSCI_PAT }}" https://raw.githubusercontent.com/demos-europe/demosplan-infrastructure/main/header_writer/headerWriter.py -O .github/headerWriter.py

      - name: Run headerWriter
        run: |
          python3 .github/headerWriter.py -p /home/runner/work/demosplan-core/demosplan-core -i  'client/js/legacy/*' 'client/js/generated/*' '*/node_modules/*' 'client/js/lib/core/SideNav.js' 'client/js/lib/core/Detabinator.js' 'demosplan/DemosPlanCoreBundle/Resources/client/js/lib/*' -a -v
        shell: bash

      - name: delete headerWriter
        run: rm .github/headerWriter.py
        shell: bash

      - name: Configure git
        run: |
          git config  user.email ${{ secrets.DEVOPS_GPG_EMAIL }}
          git config  user.name "Demos-CI"
      - name: Commit
        run: |
              git pull
              if ! git diff --exit-code; then
              git add .
              git commit -m "style: Update license header"
              git push
              fi
