name: Run FE_headerWriter

on:
  pull_request:
    paths:
      - '**.scss'
      - '**.js'
      - '**.vue'

jobs:
  FE_headerWriter:
    uses: demos-europe/demosplan-workflows/.github/workflows/FE_headerWriter.yml@main
    with:
        project_path: /home/runner/work/demosplan-core/demosplan-core
        ignore_path: client/js/legacy/*
        gpg_user_name: Demos-CI
    secrets:
        gpg_email: ${{ secrets.DEVOPS_GPG_EMAIL }}
