name: Run Reviewdog

on:
  pull_request:
    paths:
      - '**.php'
      - '**.js'
      - '**.vue'
      - 'composer.lock'

jobs:
  cancel:
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
        -   uses: styfle/cancel-workflow-action@d07a454dad7609a92316b57b23c9ccfd4f59af66
            with:
                workflow_id: "reviewdog"
                access_token: ${{ secrets.GITHUB_TOKEN }}

  reviewdog:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: actions/setup-node@v6
        with:
          node-version: '24.11.1'
      - run: npm install --ignore-scripts -g corepack && corepack enable && yarn set version 4.2.2

      - name: Cache yarn dependencies
        uses: actions/cache@v5.0.5
        with:
          path: |
            ~/.yarn/cache
            .yarn/cache
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: YARN_ENABLE_SCRIPTS=false yarn install --immutable

      - uses: reviewdog/action-setup@d8a7baabd7f3e8544ee4dbde3ee41d0011c3a93f

      - name: Setup PHP with composer v2
        uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f
        with:
          php-version: '8.2'
          extensions: gd soap sockets zip
          tools: composer:v2

      - name: Cache php modules
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae
        with:
          path: |
            ~/.composer/cache
            vendor
          key: ${{ runner.os }}-build-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-php-

      - name: Miscellaneous runtime caches
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae
        with:
          path: |
            config/.runtime/cache
          key: ${{ runner.os }}-infrastructure-runtime
          restore-keys: |
            ${{ runner.os }}-infrastructure-runtime

      - name: Install composer dependencies
        run: |
          composer --version
          composer install --no-interaction

      - name: Warmup cache
        env:
          DEVELOPMENT_CONTAINER: 1
        run: php bin/test cache:clear

      - name: Generate PHPStan config
        env:
          DEVELOPMENT_CONTAINER: 1
        run: php bin/test dplan:phpstan --only-dump-config --ci

      - name: Run linters with reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          reviewdog -reporter=github-pr-review -tee -diff="git diff ${{ github.base_ref }}"
